/**
 * Mock Task Data
 * Sample data for demo and development purposes
 */

import type { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Create Q1 Social Media Campaign',
    description: 'Design and plan the Q1 social media campaign focusing on product launches and brand awareness.',
    status: 'in_progress',
    priority: 'high',
    type: 'campaign',
    assignees: [
      { id: '1', name: 'Sarah Chen', avatar: '/avatars/sarah.jpg' },
      { id: '2', name: 'Mike Ross' },
    ],
    dueDate: '2026-02-15',
    createdAt: '2026-01-20',
    updatedAt: '2026-02-01',
    tags: ['Q1', 'Campaign', 'Social'],
    subtasks: [
      { id: 's1', title: 'Research competitor campaigns', completed: true },
      { id: 's2', title: 'Create content calendar', completed: true },
      { id: 's3', title: 'Design visual assets', completed: false },
      { id: 's4', title: 'Write copy variations', completed: false },
    ],
    comments: 12,
    attachments: 5,
    progress: 50,
    campaignId: 'camp-1',
    campaignName: 'Q1 Product Launch',
  },
  {
    id: '2',
    title: 'Analyze January Performance Metrics',
    description: 'Review and compile all social media performance metrics from January for the monthly report.',
    status: 'review',
    priority: 'medium',
    type: 'analytics',
    assignees: [{ id: '3', name: 'Alex Kim' }],
    dueDate: '2026-02-05',
    createdAt: '2026-01-28',
    updatedAt: '2026-02-02',
    tags: ['Analytics', 'Monthly', 'Report'],
    subtasks: [
      { id: 's1', title: 'Export platform data', completed: true },
      { id: 's2', title: 'Calculate engagement rates', completed: true },
      { id: 's3', title: 'Create visualizations', completed: true },
    ],
    comments: 8,
    attachments: 3,
    progress: 100,
  },
  {
    id: '3',
    title: 'Design Instagram Story Templates',
    description: 'Create a set of branded story templates for consistent Instagram presence.',
    status: 'todo',
    priority: 'medium',
    type: 'design',
    assignees: [{ id: '4', name: 'Emma Wilson', avatar: '/avatars/emma.jpg' }],
    dueDate: '2026-02-10',
    createdAt: '2026-01-30',
    updatedAt: '2026-01-30',
    tags: ['Design', 'Instagram', 'Templates'],
    subtasks: [
      { id: 's1', title: 'Create poll template', completed: false },
      { id: 's2', title: 'Create Q&A template', completed: false },
      { id: 's3', title: 'Create announcement template', completed: false },
    ],
    comments: 3,
    attachments: 1,
    progress: 0,
  },
  {
    id: '4',
    title: 'Write Blog Post: AI in Marketing',
    description: 'Draft a comprehensive blog post about how AI is transforming social media marketing.',
    status: 'in_progress',
    priority: 'low',
    type: 'content',
    assignees: [{ id: '1', name: 'Sarah Chen', avatar: '/avatars/sarah.jpg' }],
    dueDate: '2026-02-20',
    createdAt: '2026-01-25',
    updatedAt: '2026-02-01',
    tags: ['Blog', 'AI', 'Content'],
    subtasks: [
      { id: 's1', title: 'Research and outline', completed: true },
      { id: 's2', title: 'Write first draft', completed: false },
      { id: 's3', title: 'Add visuals', completed: false },
      { id: 's4', title: 'SEO optimization', completed: false },
    ],
    comments: 5,
    attachments: 2,
    progress: 25,
  },
  {
    id: '5',
    title: 'Schedule Twitter Content for Week',
    description: 'Plan and schedule all Twitter posts for the upcoming week using the content calendar.',
    status: 'done',
    priority: 'high',
    type: 'social',
    assignees: [{ id: '2', name: 'Mike Ross' }],
    dueDate: '2026-02-01',
    createdAt: '2026-01-28',
    updatedAt: '2026-02-01',
    tags: ['Twitter', 'Scheduling', 'Weekly'],
    subtasks: [
      { id: 's1', title: 'Review content calendar', completed: true },
      { id: 's2', title: 'Write tweets', completed: true },
      { id: 's3', title: 'Schedule in platform', completed: true },
    ],
    comments: 4,
    attachments: 0,
    progress: 100,
  },
  {
    id: '6',
    title: 'Urgent: Crisis Response Post',
    description: 'Prepare and publish response post regarding the recent customer feedback situation.',
    status: 'todo',
    priority: 'urgent',
    type: 'social',
    assignees: [
      { id: '1', name: 'Sarah Chen', avatar: '/avatars/sarah.jpg' },
      { id: '3', name: 'Alex Kim' },
    ],
    dueDate: '2026-02-02',
    createdAt: '2026-02-01',
    updatedAt: '2026-02-01',
    tags: ['Urgent', 'Crisis', 'Response'],
    subtasks: [
      { id: 's1', title: 'Draft response', completed: false },
      { id: 's2', title: 'Legal review', completed: false },
      { id: 's3', title: 'Publish', completed: false },
    ],
    comments: 15,
    attachments: 2,
    progress: 0,
  },
];
