/**
 * Remotion Composition Types
 *
 * Shared types for all Remotion video compositions.
 * Props map to the existing VideoGeneration.scriptContent JSON structure.
 */

/** A single scene in a video composition. */
export interface SceneProps {
  text: string;
  subtitle?: string;
  backgroundColour?: string;
  imageUrl?: string;
  /** Duration in frames (at 30fps, 30 frames = 1 second). */
  duration: number;
}

/** Audio configuration for brand video compositions. */
export interface AudioConfig {
  /**
   * Path relative to the Remotion public/ directory for the voiceover file.
   * e.g. 'audio/disaster-recovery/showcase-voice.mp3'
   * Generated by scripts/generate-brand-audio.ts via ElevenLabs TTS.
   */
  voiceoverStaticFile?: string;
  /**
   * Path relative to the Remotion public/ directory for background music.
   * e.g. 'audio/music/corporate.mp3'
   * Generated by scripts/generate-brand-audio.ts via FFmpeg synthesis.
   */
  musicStaticFile?: string;
  /** Background music volume 0–1. Default 0.12 (subtle). */
  musicVolume?: number;
}

/** Base props shared by all compositions. */
export interface BaseCompositionProps {
  title: string;
  scenes: SceneProps[];
  brandColour?: string;
  logoUrl?: string;
  audioConfig?: AudioConfig;
}

/** Props for the SocialReel composition. */
export interface SocialReelProps extends BaseCompositionProps {
  /** Aspect ratio — defaults to 9:16 (portrait for social). */
  aspectRatio?: '9:16' | '1:1' | '16:9';
  /** Show animated progress bar at bottom. */
  showProgress?: boolean;
}

/** Props for the ExplainerVideo composition. */
export interface ExplainerVideoProps extends BaseCompositionProps {
  /** Voiceover script displayed as captions. */
  voiceoverScript?: string;
  /** Transition style between scenes. */
  transition?: 'fade' | 'slide' | 'zoom';
}

/** Props for the BrandShowcase composition (16:9 landscape). */
export interface BrandShowcaseProps extends BaseCompositionProps {
  tagline: string;
  valueProps: string[];
  websiteUrl?: string;
  industry?: string;
  /** Transition style between scenes. */
  transition?: 'fade' | 'slide' | 'zoom';
}

/** Props for the BrandReel composition (9:16 portrait). */
export interface BrandReelProps extends BaseCompositionProps {
  hookText: string;
  benefit: string;
  ctaText?: string;
}

/** Props for the BrandSquare composition (1:1 square). */
export interface BrandSquareProps extends BaseCompositionProps {
  problem: string;
  solution: string;
  ctaText?: string;
}

// ── Educational Composition Props (SYN-429) ───────────────────────────────────

/** Props for the TipCard composition (9:16 portrait, 450 frames / 15s). */
export interface TipCardProps extends BaseCompositionProps {
  /** Tip number displayed in the badge (e.g. 1, 2, 3). */
  tipNumber: number;
  /** Short, bold tip headline. */
  tip: string;
  /** One-line explanation supporting the tip. */
  explanation: string;
}

/** Props for the StatReveal composition (16:9, 600 frames / 20s). */
export interface StatRevealProps extends BaseCompositionProps {
  /** The statistic to display, e.g. "73%" or "2.4x". */
  stat: string;
  /** Label describing what the stat measures. */
  statLabel: string;
  /** Additional context or source attribution for the stat. */
  context: string;
}

/** Props for the ComparisonSlide composition (16:9, 750 frames / 25s). */
export interface ComparisonSlideProps extends BaseCompositionProps {
  /** Description of the old/ineffective way. */
  oldWay: string;
  /** Description of the new/better way. */
  newWay: string;
  /** Optional label for the old-way panel. Defaults to "The Old Way". */
  oldLabel?: string;
  /** Optional label for the new-way panel. Defaults to "The New Way". */
  newLabel?: string;
}

/** Props for the ListicleVideo composition (16:9, 900 frames / 30s). */
export interface ListicleVideoProps extends BaseCompositionProps {
  /** Up to 5 list items to reveal sequentially. */
  items: string[];
}

/** A single step in a how-to guide. */
export interface HowToStep {
  /** The step instruction. */
  step: string;
  /** Optional supporting detail for the step. */
  detail?: string;
}

/** Props for the HowToVideo composition (16:9, 1200 frames / 40s). */
export interface HowToVideoProps extends BaseCompositionProps {
  /** Up to 5 steps in the guide. */
  steps: HowToStep[];
}

/** Props for the CaseStudyVideo composition (16:9, 1200 frames / 40s). */
export interface CaseStudyVideoProps extends BaseCompositionProps {
  /** Description of the client's challenge. */
  challenge: string;
  /** Description of the solution applied. */
  solution: string;
  /** Description of the result achieved. */
  result: string;
  /** Optional metric callout shown in the result scene, e.g. "+340% ROI". */
  metric?: string;
}

/** Props for the QuoteCard composition (1:1 square, 600 frames / 20s). */
export interface QuoteCardProps extends BaseCompositionProps {
  /** The quote text to display. */
  quote: string;
  /** Optional attribution, e.g. "Sarah, Small Business Owner". */
  attribution?: string;
}

/** Props for the CountdownCTA composition (16:9, 450 frames / 15s). */
export interface CountdownCTAProps extends BaseCompositionProps {
  /** Main headline driving urgency. */
  headline: string;
  /** Call-to-action button text. */
  cta: string;
  /** Optional URL to display below the CTA. */
  url?: string;
}

/** Props for the DefinitionCard composition (16:9, 600 frames / 20s). */
export interface DefinitionCardProps extends BaseCompositionProps {
  /** The marketing term being defined. */
  term: string;
  /** Clear definition of the term. */
  definition: string;
  /** Optional usage example in context. */
  example?: string;
}

// ── BTS Series Composition Props (SYN-572) ────────────────────────────────────

/** A single git commit entry for the GitCommitTimeline composition. */
export interface GitCommit {
  /** Short hash (7 chars), e.g. "abc1234". */
  hash: string;
  /** Conventional commit type: feat, fix, refactor, docs, test, chore. */
  type?: string;
  /** Conventional commit scope, e.g. "api", "video", "auth". */
  scope?: string;
  /** Commit message subject line. */
  message: string;
  /** Display date string, e.g. "2026-03-11". */
  date?: string;
}

/** Props for the GitCommitTimeline composition (16:9, 900 frames / 30s). */
export interface GitCommitTimelineProps extends BaseCompositionProps {
  /**
   * Up to 7 commits shown. Each animates in at 2-second intervals.
   * Additional commits beyond 7 are silently ignored.
   */
  commits: GitCommit[];
  /**
   * Optional one-line context shown below the title, e.g.
   * "Sprint 3 — Video Pipeline Delivery" or "Phase 6 completion".
   */
  episodeContext?: string;
}

/** Props for the BoardDecisionCard composition (16:9, 750 frames / 25s). */
export interface BoardDecisionCardProps extends BaseCompositionProps {
  /**
   * Short descriptor for what category of decision this was, e.g.
   * "Phase 4 Architecture" or "Sprint Planning".
   */
  decisionContext?: string;
  /** The decision statement — main body copy. */
  decision: string;
  /** Why this decision was made. */
  rationale?: string;
  /** What happened as a result. */
  outcome?: string;
  /** Up to 3 follow-on action items from the decision. */
  actionItems?: string[];
  /**
   * Phase label shown in the badge, e.g. "Phase 6" or "Board Session".
   * Defaults to "Board Decision".
   */
  phase?: string;
  /** Display date for the decision, e.g. "11 March 2026". */
  decisionDate?: string;
}

/** Registry entry describing a composition. */
export interface CompositionMeta {
  id: string;
  name: string;
  description: string;
  defaultProps: BaseCompositionProps;
  /** Composition dimensions. */
  width: number;
  height: number;
  fps: number;
  /** Duration in frames. */
  durationInFrames: number;
}
