/**
 * Persist approved workflow content as a ContentCalendar slot (SYN-1040 slice 2).
 *
 * Slice 1 (publish-mapping.ts) shaped approved content into a CalendarSlot; this
 * slice writes that slot into the org's ContentCalendar.slots JSONB so a later
 * slice can enqueue a PublishQueueItem from it. The scheduler still owns the
 * publish safety-gate — persisting a slot does NOT publish anything.
 *
 * Split in two: a pure `appendPublishSlot` transform (unit-testable, no DB) and a
 * thin org-scoped `persistPublishSlot` wrapper that reads + writes the calendar.
 */
import prisma from '@/lib/prisma';
import {
  workflowContentToCalendarSlot,
  type WorkflowContentToSlotInput,
} from './publish-mapping';
import type { CalendarSlot, ContentCalendarData } from '@/lib/calendar/types';

/** Thrown when no org-scoped calendar exists for the requested id. */
export class CalendarNotFoundError extends Error {
  constructor(
    public readonly organizationId: string,
    public readonly calendarId: string,
  ) {
    super(
      `persistPublishSlot: no calendar "${calendarId}" for organisation "${organizationId}"`,
    );
    this.name = 'CalendarNotFoundError';
  }
}

/** Fields needed to map + append a slot. `id` is generated by the caller below. */
export type AppendPublishSlotInput = Omit<WorkflowContentToSlotInput, 'id'> & {
  id: string;
};

/**
 * Pure transform: map approved content into a slot (slice 1) and append it to an
 * existing calendar's slot list. Returns the new calendar data plus the slot so
 * the caller can persist it and report the slot id. Throws on an unsupported
 * platform (via the slice-1 mapper) rather than mis-routing a publish.
 */
export function appendPublishSlot(
  calendar: ContentCalendarData,
  input: AppendPublishSlotInput,
): { calendar: ContentCalendarData; slot: CalendarSlot } {
  const slot = workflowContentToCalendarSlot(input);
  return {
    calendar: { ...calendar, slots: [...calendar.slots, slot] },
    slot,
  };
}

export interface PersistPublishSlotInput {
  organizationId: string;
  /** The ContentCalendar to append the approved slot to. */
  calendarId: string;
  /** Approved content output from the workflow's generate/approve step. */
  content: unknown;
  /** Target platform (validated by the slice-1 mapper). */
  platform: string;
  /** When the post should be scheduled. */
  scheduledAt: Date;
  /** Content category; defaults to 'educational' in the mapper. */
  contentType?: WorkflowContentToSlotInput['contentType'];
}

/**
 * Read the org-scoped calendar, append the mapped slot, and persist it. The
 * org-scope on the read is the cross-org guard — a calendar belonging to another
 * organisation is invisible and surfaces as CalendarNotFoundError.
 */
export async function persistPublishSlot(
  input: PersistPublishSlotInput,
): Promise<{ calendarId: string; slotId: string }> {
  const calendar = await prisma.contentCalendar.findFirst({
    where: { id: input.calendarId, organizationId: input.organizationId },
  });
  if (!calendar) {
    throw new CalendarNotFoundError(input.organizationId, input.calendarId);
  }

  const calendarData = calendar.slots as unknown as ContentCalendarData;
  const slotId = crypto.randomUUID();

  const { calendar: nextData, slot } = appendPublishSlot(calendarData, {
    id: slotId,
    content: input.content,
    platform: input.platform,
    scheduledAt: input.scheduledAt,
    contentType: input.contentType,
  });

  await prisma.contentCalendar.update({
    where: { id: input.calendarId },
    data: {
      slots: nextData as unknown as Parameters<
        typeof prisma.contentCalendar.update
      >[0]['data']['slots'],
      updatedAt: new Date(),
    },
  });

  return { calendarId: input.calendarId, slotId: slot.id };
}
