/**
 * Renders a {@link BuildLandingPageResult} into a Next.js App Router
 * `page.tsx` source file ready to commit to disasterrecovery.com.au.
 *
 * Pure function — no I/O. Caller pipes the output to GitHubClient.putFile.
 *
 * @see SYN-834 (epic — Track 2 ship-now)
 */

import type { BuildLandingPageResult } from '@/lib/landing-page';

const HEADER = `// 🤖 Auto-generated by Synthex SYN-834 NRPG → DR pipeline.
// Source-of-truth job ID is embedded in the rendered HTML comment.
// Hand-edits will be overwritten on the next regeneration.\n`;

export function renderLandingPageSource(page: BuildLandingPageResult): string {
  // The page.html already escapes user-supplied strings (see
  // lib/landing-page/page-builder.ts:renderHtml). The JSON-LD object
  // is serialised through JSON.stringify which neutralises any
  // would-be `</script>` injection.
  const jsonLdStr = JSON.stringify(page.jsonLd).replace(/</g, '\\u003c');
  // Prepare interpolated values for the template literal.
  const canonicalUrl = page.canonicalUrl;
  const html = page.html;

  return `${HEADER}
import type { Metadata } from 'next';

export const metadata: Metadata = {
  alternates: { canonical: ${JSON.stringify(canonicalUrl)} },
};

export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: ${JSON.stringify(jsonLdStr)} }}
      />
      <div dangerouslySetInnerHTML={{ __html: ${JSON.stringify(html)} }} />
    </>
  );
}
`;
}

/**
 * The repo-relative path under which the page is committed.
 * Mirrors the slug → URL mapping in lib/sitemap.
 *
 *   slug 'water-damage/brisbane-cbd' → 'app/water-damage/brisbane-cbd/page.tsx'
 */
export function pathForLandingPage(page: BuildLandingPageResult): string {
  return `app/${page.slug}/page.tsx`;
}
