import type {
  GoalContract,
  VisionMap,
  WorkPacket,
} from '@/lib/intentscape/contracts';

interface MarketingExtenderBriefInput {
  originSignal: string;
  visionMap: VisionMap;
  goalContract: GoalContract;
  workPacket: WorkPacket;
}

function list(values: readonly string[]): string {
  return values.length
    ? values.map(value => `- ${value}`).join('\n')
    : '- None';
}

export function buildMarketingExtenderBrief({
  originSignal,
  visionMap,
  goalContract,
  workPacket,
}: MarketingExtenderBriefInput): string {
  const selected = visionMap.hypotheses.find(
    hypothesis => hypothesis.id === goalContract.hypothesisId
  );

  return `# Synthex Marketing Extender — Vision Brief

## Human signal

${originSignal}

> This signal is provenance only. It is not treated as the final goal or authority to act.

## Expanded vision

${visionMap.synthesis}

### Selected direction

**${selected?.title ?? 'Approved direction'}**

${selected?.causalMechanism ?? goalContract.desiredChange}

**Desired change:** ${goalContract.desiredChange}

**Primary stakeholder:** ${goalContract.primaryStakeholder}

## Acceptance criteria

${list(goalContract.acceptanceCriteria)}

## Exclusions

${list(goalContract.exclusions)}

## Authority boundaries

${list(goalContract.authorityBoundaries)}

## Governed work packet

**Goal:** ${workPacket.goal}

**Evidence references:** ${workPacket.evidenceRefs.length}

---

Generated by Synthex Marketing Extender. The brief contains no authority to publish, purchase or take an irreversible action.
`;
}
