/**
 * Unit test — report-generator tenant scoping (cross-org leak guard).
 *
 * Regression guard: the report data-gathering queries previously filtered
 * only by date, so a report generated by one user aggregated EVERY
 * organisation's campaigns, A/B tests, analytics events and psychology
 * metrics into the downloadable export. These tests assert every gather*
 * query is scoped to the report owner's tenant:
 *   - Campaign / ABTest → organizationId when present, else userId
 *   - AnalyticsEvent     → userId
 *   - PsychologyMetric   → generation.userId
 */

const reportCreate = jest.fn();
const reportUpdate = jest.fn();
const campaignFindMany = jest.fn();
const analyticsFindMany = jest.fn();
const abTestFindMany = jest.fn();
const psychologyFindMany = jest.fn();

jest.mock('@/lib/prisma', () => ({
  __esModule: true,
  prisma: {
    report: {
      create: (...a: unknown[]) => reportCreate(...a),
      update: (...a: unknown[]) => reportUpdate(...a),
    },
    campaign: { findMany: (...a: unknown[]) => campaignFindMany(...a) },
    analyticsEvent: { findMany: (...a: unknown[]) => analyticsFindMany(...a) },
    aBTest: { findMany: (...a: unknown[]) => abTestFindMany(...a) },
    psychologyMetric: { findMany: (...a: unknown[]) => psychologyFindMany(...a) },
  },
}));

const getEffectiveOrganizationId = jest.fn();
jest.mock('@/lib/multi-business/business-scope', () => ({
  __esModule: true,
  getEffectiveOrganizationId: (...a: unknown[]) =>
    getEffectiveOrganizationId(...a),
}));

import { reportGenerator } from '@/lib/reports/report-generator';

/** Flush pending microtasks/timers until `cond` is true (fire-and-forget chain). */
async function waitFor(cond: () => boolean, tries = 50): Promise<void> {
  for (let i = 0; i < tries; i++) {
    if (cond()) return;
    await Promise.resolve();
    await new Promise(r => setTimeout(r, 0));
  }
  throw new Error('condition not met in time');
}

const DATE_RANGE = { start: '2026-01-01', end: '2026-02-01' };

beforeEach(() => {
  jest.clearAllMocks();
  reportCreate.mockResolvedValue({ id: 'rep-1' });
  reportUpdate.mockResolvedValue({});
  campaignFindMany.mockResolvedValue([]);
  analyticsFindMany.mockResolvedValue([]);
  abTestFindMany.mockResolvedValue([]);
  psychologyFindMany.mockResolvedValue([]);
});

describe('report-generator tenant scoping', () => {
  test('persists the effective organizationId on the report record', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    const res = await reportGenerator.generateReport('user-1', {
      name: 'Q1',
      type: 'campaign',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    expect(res.reportId).toBe('rep-1');
    expect(getEffectiveOrganizationId).toHaveBeenCalledWith('user-1');
    expect(reportCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          userId: 'user-1',
          organizationId: 'org-A',
        }),
      })
    );
  });

  test('campaign query is scoped by organizationId when the user has an org', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    await reportGenerator.generateReport('user-1', {
      name: 'Campaigns',
      type: 'campaign',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(() => campaignFindMany.mock.calls.length > 0);
    const where = campaignFindMany.mock.calls[0][0].where;
    expect(where).toMatchObject({ organizationId: 'org-A' });
    expect(where.userId).toBeUndefined();
  });

  test('campaign query falls back to userId when the user has no org', async () => {
    getEffectiveOrganizationId.mockResolvedValue(null);

    await reportGenerator.generateReport('user-1', {
      name: 'Campaigns',
      type: 'campaign',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(() => campaignFindMany.mock.calls.length > 0);
    const where = campaignFindMany.mock.calls[0][0].where;
    expect(where).toMatchObject({ userId: 'user-1' });
    expect(where.organizationId).toBeUndefined();
  });

  test('ab-test query is scoped by organizationId', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    await reportGenerator.generateReport('user-1', {
      name: 'AB',
      type: 'ab-test',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(() => abTestFindMany.mock.calls.length > 0);
    expect(abTestFindMany.mock.calls[0][0].where).toMatchObject({
      organizationId: 'org-A',
    });
  });

  test('analytics query is scoped by userId', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    await reportGenerator.generateReport('user-1', {
      name: 'Analytics',
      type: 'analytics',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(() => analyticsFindMany.mock.calls.length > 0);
    expect(analyticsFindMany.mock.calls[0][0].where).toMatchObject({
      userId: 'user-1',
    });
  });

  test('psychology query is scoped via owning generation userId', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    await reportGenerator.generateReport('user-1', {
      name: 'Psych',
      type: 'psychology',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(() => psychologyFindMany.mock.calls.length > 0);
    expect(psychologyFindMany.mock.calls[0][0].where).toMatchObject({
      generation: { userId: 'user-1' },
    });
  });

  test('comprehensive report scopes ALL four sources to the same tenant', async () => {
    getEffectiveOrganizationId.mockResolvedValue('org-A');

    await reportGenerator.generateReport('user-1', {
      name: 'Everything',
      type: 'comprehensive',
      format: 'json',
      dateRange: DATE_RANGE,
    });

    await waitFor(
      () =>
        campaignFindMany.mock.calls.length > 0 &&
        analyticsFindMany.mock.calls.length > 0 &&
        abTestFindMany.mock.calls.length > 0 &&
        psychologyFindMany.mock.calls.length > 0
    );

    expect(campaignFindMany.mock.calls[0][0].where).toMatchObject({
      organizationId: 'org-A',
    });
    expect(abTestFindMany.mock.calls[0][0].where).toMatchObject({
      organizationId: 'org-A',
    });
    expect(analyticsFindMany.mock.calls[0][0].where).toMatchObject({
      userId: 'user-1',
    });
    expect(psychologyFindMany.mock.calls[0][0].where).toMatchObject({
      generation: { userId: 'user-1' },
    });
  });
});
