-- SYN-964: revoke REST-layer EXECUTE on internal SECURITY DEFINER functions
-- CANDIDATE MIGRATION — NOT APPLIED. Prod apply = founder gate. Review first.
--
-- Method: 178 SECURITY DEFINER fns in public that are NOT called via
-- supabase.rpc() anywhere in app/lib/components/supabase/scripts/board-cron. They run
-- with definer rights when invoked by triggers/other functions, so a direct
-- anon/authenticated EXECUTE grant is unnecessary REST exposure (what the advisor flags).
-- Clears ~356 of 358 SECURITY DEFINER advisories → total 378 → ~22.
--
-- EXCLUDED (app calls via .rpc(), keep grants — review anon-vs-authenticated separately):
--   get_anniversary_orgs
-- DETECTION LIMITS (verify before apply): only .rpc() string-literal calls were scanned;
-- dynamic rpc(name), pg_cron jobs, and psql/raw callers are NOT covered.

BEGIN;

REVOKE EXECUTE ON FUNCTION public."add_correction_graph_node"(p_cycle_id uuid, p_node_type text, p_severity integer, p_related_agent text, p_related_memory_id uuid, p_related_task_id uuid, p_link_type text, p_confidence integer, p_notes text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."approve_blueprint_channel"(p_blueprint_id uuid, p_channel text, p_approved_by uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."archive_safety_action"(p_workspace_id uuid, p_action text, p_trigger_event uuid, p_risk_before integer, p_risk_after integer, p_uncertainty_before integer, p_uncertainty_after integer, p_affected_agents text[], p_metadata jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."calculate_alert_health"(p_framework_id uuid, p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."calculate_domain_health"(p_owner_user_id uuid, p_domain text, p_business_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."calculate_pre_client_score"(p_pre_client_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_ai_budget"(p_workspace_id uuid, p_period text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_connection_pool_status"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_posts_milestone"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_token_expiry"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_usage_limit"(p_org_id uuid, p_counter_type text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_views_milestone"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."check_workspace_permission"(p_user_id uuid, p_workspace_id uuid, p_permission text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."cleanup_old_observability_logs"(days_to_keep integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."cleanup_pipeline_memory"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."cleanup_rate_limit_logs"(days_to_keep integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."complete_managed_task"(p_task_id uuid, p_output_data jsonb, p_notes text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."convert_trial_to_paid"(p_workspace_id uuid, p_converted_by uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."convex_get_workspace_stats"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."convex_increment_framework_usage"(p_workspace_id uuid, p_framework_id character varying, p_framework_category character varying, p_score integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."create_blueprint_revision"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."create_calibration_cycle"(p_workspace_id uuid, p_analysis_start_time timestamp with time zone, p_analysis_end_time timestamp with time zone, p_metrics_analyzed jsonb, p_proposed_changes jsonb, p_change_rationale text, p_requires_approval boolean) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."create_correction_cycle"(p_workspace_id uuid, p_cycle_type text, p_description text, p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."create_global_autonomy_run"(p_workspace_id uuid, p_objective text, p_description text, p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."create_safety_event"(p_workspace_id uuid, p_event_type text, p_severity integer, p_risk_level integer, p_source text, p_details jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."generate_referral_code"(p_workspace_id uuid, p_user_id uuid, p_campaign character varying) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."generate_usage_rollup"(p_org_id uuid, p_workspace_id uuid, p_period_type text, p_period_start timestamp with time zone, p_period_end timestamp with time zone) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_agent_runs"(p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_boost_jobs"(p_business_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_coalition_proposals"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_integration_token"(p_workspace_id uuid, p_integration_type text, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_integrations"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_marketplace_auctions"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_negotiation_session"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_active_projects"(p_tenant_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_ai_cost_breakdown"(p_workspace_id uuid, p_start_date date, p_end_date date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_alert_stats"(p_framework_id uuid, p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_alert_trend"(p_framework_id uuid, p_workspace_id uuid, p_days integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_analytics_cache"(p_workspace_id uuid, p_brand_slug text, p_metric_name text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_analytics_cache_status"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_audit_events"(p_org_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone, p_category text, p_severity text, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_autonomous_task_summary"(p_workspace_id uuid, p_task_type text, p_hours_back integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_available_rewards"(p_workspace_id uuid, p_user_credits bigint) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_blueprint_stats"(p_workspace_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_boost_performance_summary"(p_job_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_brand_activity_summary"(p_workspace_id uuid, p_brand_slug text, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_brand_channels"(p_workspace_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_brand_task_metrics"(p_workspace_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_bu_hierarchy"(p_bu_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_campaign_blueprints"(p_workspace_id uuid, p_brand_slug text, p_status text, p_type text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_channel_templates"(p_workspace_id uuid, p_channel_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_client_email_intelligence"(p_workspace_id uuid, p_client_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_coalition_analytics"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_cognitive_twin_dashboard"(p_owner_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_current_usage"(p_org_id uuid, p_counter_type text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_dataforseo_cache"(p_workspace_id uuid, p_brand_slug text, p_keyword text, p_api_endpoint text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_digest_history"(p_owner_user_id uuid, p_digest_type text, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_effective_org_permissions"(p_user_id uuid, p_org_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_archive_stats"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_brand_history"(p_workspace_id uuid, p_brand_slug text, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_daily_queue"(p_workspace_id uuid, p_date date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_task_history"(p_workspace_id uuid, p_task_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_tasks_by_brand"(p_workspace_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_tasks_by_status"(p_workspace_id uuid, p_status text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_founder_ops_weekly_queue"(p_workspace_id uuid, p_start_date date, p_end_date date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_hot_pre_clients"(p_owner_user_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_keyword_opportunities"(p_business_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_latest_founder_momentum"(p_founder_id uuid, p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_latest_sync_status"(p_domain text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_loyalty_monthly_progress"(p_workspace_id uuid, p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_marketplace_statistics"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_mindmap_structure"(p_mindmap_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_negotiation_stats"(p_workspace_id uuid, p_lookback_days integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_next_scheduled_sync"(p_domain text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_oauth_token"(p_workspace_id uuid, p_provider text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_org_subscription"(p_org_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_org_usage_summary"(p_org_id uuid, p_period_start timestamp with time zone, p_period_end timestamp with time zone) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_org_workspace_count"(p_org_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pending_decisions"(p_owner_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pending_email_actions"(p_workspace_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pending_tasks"(p_project_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pending_tasks_for_agent"(p_agent_name text, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pipeline_memory"(p_client_id text, p_pipeline_id text, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_portfolio_health_summary"(p_owner_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_pre_client_overview"(p_owner_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_queue_status"(p_workspace_id uuid, p_date date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_rate_limit_override"(client_key_param text, endpoint_param text, workspace_id_param uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_search_console_cache"(p_workspace_id uuid, p_brand_slug text, p_data_source text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_search_console_cache"(p_workspace_id uuid, p_domain text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_seasonal_signals"(p_industry_slug text, p_state_code text, p_lookahead_weeks integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_social_inbox_summary"(p_business_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_token_usage_stats"(p_workspace_id uuid, p_integration_type text, p_days integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_top_founder_opportunities"(p_founder_id uuid, p_workspace_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_top_founder_risks"(p_founder_id uuid, p_workspace_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_trial_activity"(p_workspace_id uuid, p_limit integer, p_activity_type text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_trial_activity_summary"(p_workspace_id uuid, p_since timestamp with time zone) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_trial_limit_hits"(p_workspace_id uuid, p_limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_trial_status"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_trial_upgrade_prompt_history"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_agencies"(p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_org_role"(user_uuid uuid, org_uuid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_role"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_stats"(user_uuid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_teams"(p_user_id uuid, p_org_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_workspaces"(p_user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_user_workspaces"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."get_workspace_limit"(workspace_id_param uuid, limit_name text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."handle_redemption_request"(p_request_id uuid, p_workspace_id uuid, p_approved boolean, p_founder_notes text, p_transparency_message text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."handle_user_organization_assignment"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."has_oauth_token"(p_workspace_id uuid, p_provider text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."has_role"(VARIADIC allowed_roles text[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_template_usage"(p_template_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_token_error"(p_token_id uuid, p_error_message text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_trial_ai_usage"(p_workspace_id uuid, p_tokens_used integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_trial_blueprint_usage"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_trial_vif_usage"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."increment_usage"(p_org_id uuid, p_counter_type text, p_amount integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."invalidate_analytics_cache"(p_workspace_id uuid, p_brand_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_client"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_founder"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_ip_blocked"(ip_param text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_module_enabled_for_trial"(p_workspace_id uuid, p_module_name text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_org_member"(check_org_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_staff"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_team_member"(row_org_id text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_token_expired"(p_token_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_workspace_admin"(check_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."is_workspace_member"(check_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."issue_loyalty_credits"(p_workspace_id uuid, p_user_id uuid, p_amount bigint, p_transaction_type character varying, p_related_entity_type character varying, p_related_entity_id uuid, p_details jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."link_autonomy_to_memory"(p_run_id uuid, p_memory_id uuid, p_agent text, p_link_type text, p_confidence integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."link_autonomy_to_orchestrator"(p_run_id uuid, p_step_id uuid, p_agent text, p_link_type text, p_confidence integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_ai_usage"(p_workspace_id uuid, p_user_id uuid, p_provider text, p_model_id text, p_task_type text, p_tokens_input integer, p_tokens_output integer, p_cost_usd numeric, p_latency_ms integer, p_success boolean, p_error_message text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_audit_event"(p_org_id uuid, p_workspace_id uuid, p_user_id uuid, p_event_type text, p_event_category text, p_action text, p_severity text, p_resource_type text, p_resource_id text, p_old_value jsonb, p_new_value jsonb, p_metadata jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_convex_change"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_founder_memory_changes"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_founder_ops_archive_entry"(p_workspace_id uuid, p_entry_type text, p_task_id uuid, p_brand_slug text, p_archetype text, p_user_id uuid, p_metadata jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_rate_limit"(client_key_param text, endpoint_param text, tier_param text, allowed_param boolean, remaining_param integer, reset_at_param timestamp with time zone, method_param text, status_param integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_token_usage"(p_token_id uuid, p_operation text, p_success boolean, p_error_message text, p_api_endpoint text, p_request_params jsonb, p_response_status integer, p_duration_ms integer, p_data_cached boolean, p_cache_table text, p_records_cached integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."log_trial_activity"(p_workspace_id uuid, p_user_id uuid, p_activity_type text, p_activity_category text, p_context jsonb, p_user_message text, p_system_action text, p_ip_address inet, p_user_agent text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."mark_sync_completed"(p_domain text, p_sync_type text, p_status text, p_records integer, p_error_message text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."notify_critical_churn"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."pause_founder_ops_queue"(p_workspace_id uuid, p_date date, p_user_id uuid, p_reason text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_agent_heartbeat"(p_agent_name text, p_status text, p_metrics jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_autonomy_event"(p_run_id uuid, p_event_type text, p_severity integer, p_agent text, p_source_type text, p_source_id uuid, p_payload jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_calibration_metric"(p_workspace_id uuid, p_metric_type text, p_metric_value numeric, p_agent_name text, p_workflow_type text, p_details jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_decision_outcome"(p_decision_id uuid, p_human_decision text, p_outcome jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_referral_event"(p_workspace_id uuid, p_referrer_id uuid, p_referral_code_id uuid, p_event_type character varying, p_referred_user_id uuid, p_referred_email character varying) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_safety_prediction"(p_workspace_id uuid, p_prediction_type text, p_probability integer, p_confidence integer, p_affected_agents text[], p_recommended_action text, p_action_priority text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."record_trial_upgrade_prompt"(p_workspace_id uuid, p_was_declined boolean) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."redeem_loyalty_credits"(p_workspace_id uuid, p_user_id uuid, p_amount bigint, p_reward_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."refresh_ai_daily_summary"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."refresh_client_profitability_mv"() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."refresh_oauth_token"(p_token_id uuid, p_new_access_token text, p_new_refresh_token text, p_expires_in_seconds integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."refresh_oauth_token"(p_workspace_id uuid, p_provider text, p_new_access_token text, p_new_expires_at timestamp with time zone) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."reorder_founder_ops_queue"(p_workspace_id uuid, p_date date, p_task_ids uuid[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."resume_founder_ops_queue"(p_workspace_id uuid, p_date date) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."seed_default_channels"(p_workspace_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."set_autonomy_active_agents"(p_run_id uuid, p_agents text[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."set_correction_actions"(p_cycle_id uuid, p_improvement_actions jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."set_correction_affected_agents"(p_cycle_id uuid, p_agents text[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."submit_redemption_request"(p_workspace_id uuid, p_user_id uuid, p_reward_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_autonomy_scores"(p_run_id uuid, p_status text, p_risk_score integer, p_uncertainty_score integer, p_autonomy_score integer, p_readiness_score integer, p_consistency_score integer, p_confidence_score integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_autonomy_step_counts"(p_run_id uuid, p_total_steps integer, p_completed_steps integer, p_failed_steps integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_calibration_parameters"(p_workspace_id uuid, p_parameter_name text, p_new_value numeric, p_calibration_cycle_id uuid, p_confidence_score integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_correction_scores"(p_cycle_id uuid, p_status text, p_predicted_failure_probability integer, p_confidence integer, p_risk_score integer, p_effectiveness_score integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_safety_event_status"(p_event_id uuid, p_intervention text, p_resolved boolean, p_resolution_notes text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_task_status"(p_task_id uuid, p_status text, p_result jsonb, p_error text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."update_token_last_used"(p_token_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."upsert_self_healing_job"(p_route text, p_error_signature text, p_error_category text, p_severity text, p_ai_summary text, p_observability_log_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."user_has_org_permission"(user_uuid uuid, org_uuid uuid, required_role text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."user_has_role_in_org"(p_org_id uuid, p_required_role text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."user_has_role_in_org_simple"(p_org_id uuid, p_required_role text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."user_has_tenant_access"(p_user_id uuid, p_tenant_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."user_has_workspace_access"(ws_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."validate_referral_attribution"(p_workspace_id uuid, p_referrer_id uuid, p_referred_user_id uuid, p_referral_code_id uuid, p_referral_event_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."workspace_has_feature"(workspace_id_param uuid, feature_name text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."workspace_has_tier"(workspace_id_param uuid, required_tier text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public."workspace_within_limit"(workspace_id_param uuid, limit_name text, current_count integer) FROM anon, authenticated;

COMMIT;
