import {
  Search, FileText, BarChart3, Calendar, Settings, User, Plus, Sparkles,
  TrendingUp, LogOut, Home, File, Beaker, CreditCard, Users, Target, Brain,
  HelpCircle, Layers, Lightbulb, Layout, Zap, Link2,
  GitBranch as GitPullRequest, MessageSquare, Shield, Code, Image,
  Repeat, Send, Bell, Grid, DollarSign, Calculator, Briefcase, Link, List,
  Mic, Award, Building2, Newspaper, ShieldExclamation, CommandLine,
} from '@/components/icons';
import { notify } from '@/lib/notifications';
import type { CommandItem } from './types';

export function buildCommands(
  push: (path: string) => void
): CommandItem[] {
  return [
    // Navigation
    { id: 'dashboard', title: 'Go to Dashboard', icon: Home, action: () => push('/dashboard'), category: 'navigation', keywords: ['home', 'dashboard', 'main'] },
    { id: 'content', title: 'Content Generator', icon: FileText, action: () => push('/dashboard/content'), category: 'navigation', keywords: ['content', 'generate', 'create', 'write'] },
    { id: 'content-optimizer', title: 'Content Optimizer', description: 'Score and optimize content quality', icon: Sparkles, action: () => push('/dashboard/content/optimize'), category: 'navigation', keywords: ['optimize', 'score', 'quality', 'improve', 'suggestions', 'content optimizer'] },
    { id: 'content-performance', title: 'Content Performance', description: 'AI analysis of what content works', icon: BarChart3, action: () => push('/dashboard/content/performance'), category: 'navigation', keywords: ['performance', 'analytics', 'ai', 'insights', 'what works', 'patterns', 'engagement'] },
    { id: 'multi-format', title: 'Multi-format Generator', description: 'Generate content for multiple platforms at once', icon: Layers, action: () => push('/dashboard/content/multi-format'), category: 'navigation', keywords: ['multi-format', 'platforms', 'generate', 'variations', 'cross-platform', 'adapt', 'convert'] },
    { id: 'repurpose', title: 'Content Repurposer', description: 'Transform long-form content into threads, video scripts, and more', icon: Repeat, action: () => push('/dashboard/content/repurpose'), category: 'navigation', keywords: ['repurpose', 'transform', 'blog', 'thread', 'video script', 'carousel', 'summary', 'takeaways', 'transcript', 'podcast'] },
    { id: 'cross-post', title: 'Cross-Post', description: 'Publish content to multiple platforms with AI-powered adaptation', icon: Send, action: () => push('/dashboard/content/cross-post'), category: 'navigation', keywords: ['cross-post', 'cross post', 'publish', 'multi-platform', 'post everywhere', 'broadcast', 'distribute', 'social media'] },
    { id: 'analytics', title: 'Analytics', icon: BarChart3, action: () => push('/dashboard/analytics'), category: 'navigation', keywords: ['analytics', 'stats', 'metrics', 'data'] },
    { id: 'predictions', title: 'Predictive Analytics', description: 'ML-powered engagement predictions and optimal posting times', icon: Lightbulb, action: () => push('/dashboard/predictions'), category: 'navigation', keywords: ['predict', 'forecast', 'engagement', 'optimal', 'best time', 'ml', 'ai', 'prediction'] },
    { id: 'schedule', title: 'Schedule', icon: Calendar, action: () => push('/dashboard/schedule'), category: 'navigation', keywords: ['schedule', 'calendar', 'plan'] },
    { id: 'queue', title: 'Go to Queue', description: 'Manage and bulk-action pending posts', icon: List, action: () => push('/dashboard/schedule/queue'), category: 'navigation', keywords: ['queue', 'bulk', 'schedule', 'posts', 'pending', 'manage'] },
    { id: 'bulk-schedule', title: 'Bulk Schedule Posts', description: 'Select and reschedule multiple posts at once', icon: List, action: () => push('/dashboard/schedule/queue'), category: 'actions', keywords: ['bulk', 'schedule', 'reschedule', 'batch', 'multiple', 'posts'] },
    { id: 'calendar', title: 'Go to Calendar', description: 'Visual content calendar with drag-drop scheduling', icon: Calendar, action: () => push('/dashboard/calendar'), category: 'navigation', keywords: ['calendar', 'week', 'month', 'schedule', 'drag', 'drop'] },
    { id: 'schedule-post', title: 'Schedule Post', description: 'Open quick scheduler to add a new post', icon: Plus, action: () => push('/dashboard/calendar?action=schedule'), category: 'actions', keywords: ['schedule', 'post', 'create', 'new', 'add', 'content'] },
    { id: 'reports', title: 'Reports', description: 'Generate performance reports', icon: File, action: () => push('/dashboard/reports'), category: 'navigation', keywords: ['reports', 'generate', 'export', 'pdf'] },
    { id: 'report-builder', title: 'Report Builder', description: 'Create custom report templates with drag-drop widgets', icon: Layout, action: () => push('/dashboard/reports/builder'), category: 'navigation', keywords: ['report', 'builder', 'custom', 'template', 'widget', 'drag', 'drop'] },
    { id: 'benchmark-reports', title: 'Benchmark Reports', description: 'Compare your performance to industry standards', icon: Target, action: () => push('/dashboard/analytics/benchmarks'), category: 'navigation', keywords: ['benchmark', 'compare', 'industry', 'standards', 'performance', 'percentile'] },
    { id: 'revenue-tracker', title: 'Revenue Tracker', description: 'Track income from sponsorships, affiliates, and more', icon: DollarSign, action: () => push('/dashboard/revenue'), category: 'navigation', keywords: ['revenue', 'income', 'money', 'earnings', 'sponsorship', 'affiliate', 'monetization'] },
    { id: 'roi-calculator', title: 'ROI Calculator', description: 'Calculate return on content investment', icon: Calculator, action: () => push('/dashboard/roi'), category: 'navigation', keywords: ['roi', 'return', 'investment', 'calculator', 'profit', 'hours', 'time'] },
    { id: 'sponsor-crm', title: 'Sponsor CRM', description: 'Manage brand deals and deliverables', icon: Briefcase, action: () => push('/dashboard/sponsors'), category: 'navigation', keywords: ['sponsor', 'crm', 'brand', 'deal', 'partnership', 'deliverable', 'contract'] },
    { id: 'affiliate-links', title: 'Affiliate Links', description: 'Manage affiliate networks and track links', icon: Link, action: () => push('/dashboard/affiliates'), category: 'navigation', keywords: ['affiliate', 'links', 'tracking', 'amazon', 'network', 'commission', 'revenue'] },
    { id: 'experiments', title: 'Experiments', description: 'A/B testing and optimization', icon: Beaker, action: () => push('/dashboard/experiments'), category: 'navigation', keywords: ['experiments', 'ab testing', 'test', 'variants'] },
    { id: 'personas', title: 'Personas', description: 'AI brand voice personas', icon: Brain, action: () => push('/dashboard/personas'), category: 'navigation', keywords: ['personas', 'brand voice', 'ai'] },
    { id: 'ai-chat', title: 'AI Chat Assistant', description: 'Get AI-powered help with content strategy', icon: MessageSquare, action: () => push('/dashboard/ai-chat'), category: 'navigation', keywords: ['ai', 'chat', 'assistant', 'help', 'strategy', 'ideas', 'conversation'] },
    { id: 'ai-images', title: 'AI Images', description: 'Generate images with AI', icon: Image, action: () => push('/dashboard/ai-images'), category: 'navigation', keywords: ['image', 'generate', 'ai', 'visual', 'picture', 'dalle', 'stability', 'gemini'] },
    { id: 'competitors', title: 'Competitors', description: 'Track competitor activity', icon: Target, action: () => push('/dashboard/competitors'), category: 'navigation', keywords: ['competitors', 'competition', 'tracking'] },
    { id: 'social-listening', title: 'Social Listening', description: 'Monitor brand mentions, keywords, and hashtags', icon: Bell, action: () => push('/dashboard/listening'), category: 'navigation', keywords: ['listening', 'mentions', 'brand', 'monitor', 'keywords', 'hashtags', 'sentiment', 'social'] },
    { id: 'link-in-bio', title: 'Link in Bio Pages', description: 'Create and manage customizable landing pages', icon: Link2, action: () => push('/dashboard/bio'), category: 'navigation', keywords: ['bio', 'link', 'linktree', 'landing', 'page', 'profile', 'links'] },
    { id: 'unified-dashboard', title: 'Unified Dashboard', description: 'View all platform metrics in one place', icon: Grid, action: () => push('/dashboard/unified'), category: 'navigation', keywords: ['unified', 'all', 'platforms', 'metrics', 'overview', 'compare', 'aggregate'] },
    { id: 'audience-insights', title: 'Audience Insights', description: 'View follower demographics and behavior', icon: Users, action: () => push('/dashboard/audience'), category: 'navigation', keywords: ['audience', 'demographics', 'followers', 'insights', 'age', 'gender', 'location'] },
    { id: 'team', title: 'Team', description: 'Manage team members', icon: Users, action: () => push('/dashboard/team'), category: 'navigation', keywords: ['team', 'members', 'collaboration'] },
    { id: 'integrations', title: 'Integrations', description: 'Manage platform and third-party connections', icon: Zap, action: () => push('/dashboard/integrations'), category: 'navigation', keywords: ['integrations', 'connect', 'canva', 'buffer', 'zapier', 'third-party', 'tools'] },
    { id: 'webhooks', title: 'Webhooks', description: 'Send real-time event notifications to external systems', icon: Link2, action: () => push('/dashboard/webhooks'), category: 'navigation', keywords: ['webhooks', 'webhook', 'endpoints', 'subscriptions', 'events', 'notifications', 'outbound'] },
    { id: 'approvals', title: 'Approvals', description: 'Review and approve content before publishing', icon: GitPullRequest, action: () => push('/dashboard/approvals'), category: 'navigation', keywords: ['approvals', 'approval', 'workflow', 'review', 'approve', 'reject', 'content', 'pending'] },
    { id: 'collaboration', title: 'Team Collaboration', description: 'Activity feed, comments, and shared content', icon: MessageSquare, action: () => push('/dashboard/collaboration'), category: 'navigation', keywords: ['collaboration', 'team', 'activity', 'comments', 'shares', 'feed', 'assign'] },
    { id: 'roles', title: 'Role Management', description: 'Manage roles and permissions', icon: Shield, action: () => push('/dashboard/roles'), category: 'navigation', keywords: ['roles', 'permissions', 'access', 'rbac', 'admin', 'editor', 'viewer', 'grant', 'revoke'] },
    { id: 'technical-seo', title: 'Technical SEO', description: 'Core Web Vitals, mobile parity, robots.txt validation', icon: Search, action: () => push('/dashboard/seo/technical'), category: 'navigation', keywords: ['cwv', 'core web vitals', 'mobile', 'parity', 'robots', 'technical', 'seo', 'performance'] },
    { id: 'search-console', title: 'Search Console', description: 'Search analytics, indexing status, sitemap health', icon: BarChart3, action: () => push('/dashboard/seo/search-console'), category: 'navigation', keywords: ['search console', 'gsc', 'google', 'indexing', 'sitemap', 'queries', 'clicks', 'impressions', 'ctr'] },
    { id: 'pagespeed-insights', title: 'PageSpeed Insights', description: 'Page performance analysis, CWV monitoring, Lighthouse scores', icon: Zap, action: () => push('/dashboard/seo/pagespeed'), category: 'navigation', keywords: ['pagespeed', 'page speed', 'lighthouse', 'cwv', 'core web vitals', 'performance', 'lcp', 'cls', 'inp', 'speed'] },
    { id: 'schema-markup-manager', title: 'Schema Markup Manager', description: 'Create, validate, and manage JSON-LD structured data', icon: Code, action: () => push('/dashboard/seo/schema'), category: 'navigation', keywords: ['schema', 'json-ld', 'structured data', 'markup', 'rich results', 'rich snippets', 'organization', 'product', 'article', 'faq', 'seo', 'validator', 'template'] },
    { id: 'geo-readiness', title: 'GEO Readiness Dashboard', description: 'AI search citability scores, passage analysis, platform optimization', icon: Search, action: () => push('/dashboard/seo/geo-readiness'), category: 'navigation', keywords: ['geo', 'generative engine', 'ai search', 'citability', 'passages', 'readiness', 'google aio', 'chatgpt', 'perplexity', 'bing copilot', 'ai visibility'] },
    { id: 'voice-fingerprint', title: 'Voice Engine — Fingerprint', description: 'Analyse your writing style and generate a voice fingerprint', icon: Mic, action: () => push('/dashboard/voice?tab=fingerprint'), category: 'navigation', keywords: ['voice', 'fingerprint', 'writing style', 'stylometric', 'analyse'] },
    { id: 'voice-capsule', title: 'Voice Engine — Content Capsule', description: 'Format content for AI citation and extractability', icon: FileText, action: () => push('/dashboard/voice?tab=capsule'), category: 'navigation', keywords: ['voice', 'capsule', 'content capsule', 'ai citation', 'extractability', 'format'] },
    { id: 'voice-slop', title: 'Voice Engine — Slop Scan', description: 'Scan content for AI tell-phrases and overused language', icon: Search, action: () => push('/dashboard/voice?tab=slop'), category: 'navigation', keywords: ['voice', 'slop', 'slop scan', 'ai phrases', 'tell-phrases', 'overused', 'scan'] },
    { id: 'quality-audit', title: 'Quality Gate — Run Audit', description: 'Score content humanness and detect AI tell-phrases', icon: Shield, action: () => push('/dashboard/quality'), category: 'navigation', keywords: ['quality', 'gate', 'audit', 'humanness', 'slop', 'ai', 'detect', 'score'] },
    { id: 'quality-history', title: 'Quality Gate — Audit History', description: 'View previously saved quality audits', icon: Shield, action: () => push('/dashboard/quality?tab=history'), category: 'navigation', keywords: ['quality', 'gate', 'history', 'saved', 'audits', 'previous'] },
    { id: 'eeat-audit', title: 'E-E-A-T — Run Audit', description: 'Score content across Experience, Expertise, Authority, and Trust', icon: Award, action: () => push('/dashboard/eeat'), category: 'navigation', keywords: ['eeat', 'e-e-a-t', 'experience', 'expertise', 'authority', 'trust', 'audit', 'score', 'google', 'content quality'] },
    { id: 'eeat-assets', title: 'E-E-A-T — Generate Assets', description: 'Generate templates to fill E-E-A-T signal gaps', icon: Award, action: () => push('/dashboard/eeat?tab=assets'), category: 'navigation', keywords: ['eeat', 'e-e-a-t', 'assets', 'templates', 'generate', 'author bio', 'schema', 'trust signal', 'citation'] },
    { id: 'brand-identity', title: 'Brand Builder — Identity', description: 'Create and manage your brand entity profile', icon: Building2, action: () => push('/dashboard/brand'), category: 'navigation', keywords: ['brand', 'identity', 'entity', 'profile', 'knowledge panel', 'wikidata', 'nap', 'consistency'] },
    { id: 'brand-consistency', title: 'Brand Builder — Consistency Audit', description: 'Check NAP consistency across all brand platforms', icon: Building2, action: () => push('/dashboard/brand?tab=consistency'), category: 'navigation', keywords: ['brand', 'consistency', 'nap', 'audit', 'platforms', 'wikidata', 'knowledge graph'] },
    { id: 'brand-mentions', title: 'Brand Builder — Mentions', description: 'Monitor brand mentions across news and media', icon: Building2, action: () => push('/dashboard/brand?tab=mentions'), category: 'navigation', keywords: ['brand', 'mentions', 'monitor', 'news', 'media', 'sentiment', 'newsdata', 'gdelt'] },

    // PR Manager (Phase 92)
    { id: 'pr-journalists', title: 'PR Manager — Journalists', description: 'Manage journalist contacts and pitches', icon: Newspaper, action: () => push('/dashboard/pr'), category: 'navigation', keywords: ['pr', 'journalist', 'pitch', 'media', 'press', 'contact', 'crm', 'outreach'] },
    { id: 'pr-pitches', title: 'PR Manager — Pitches', description: 'Track pitch lifecycle and status', icon: Newspaper, action: () => push('/dashboard/pr?tab=pitches'), category: 'navigation', keywords: ['pitch', 'outreach', 'journalist', 'sent', 'replied', 'covered', 'pr', 'kanban'] },
    { id: 'pr-coverage', title: 'PR Manager — Coverage', description: 'Monitor editorial coverage and poll for mentions', icon: Newspaper, action: () => push('/dashboard/pr?tab=coverage'), category: 'navigation', keywords: ['coverage', 'editorial', 'mention', 'media', 'press', 'poll', 'gdelt', 'newsdata'] },
    { id: 'pr-press-releases', title: 'PR Manager — Press Releases', description: 'Create AI-indexable press releases with schema.org JSON-LD', icon: Newspaper, action: () => push('/dashboard/pr?tab=press-releases'), category: 'navigation', keywords: ['press release', 'newsroom', 'schema', 'json-ld', 'publish', 'ai indexing'] },

    // Awards & Directories (Phase 94)
    { id: 'awards-tracker', title: 'Awards & Directories — Tracker', description: 'Track award nominations and directory listings for E-E-A-T and backlinks', icon: Award, action: () => push('/dashboard/awards'), category: 'navigation', keywords: ['awards', 'directories', 'tracker', 'nominations', 'backlinks', 'eeat', 'listing', 'submission', 'industry award'] },
    { id: 'awards-deadlines', title: 'Awards & Directories — Deadlines', description: 'View upcoming award submission deadlines within 90 days', icon: Award, action: () => push('/dashboard/awards?tab=deadlines'), category: 'navigation', keywords: ['awards', 'deadlines', 'submission', 'due date', 'calendar', 'upcoming', 'reminder'] },
    // AI Backlink Prospector (Phase 95)
    { id: 'backlinks-prospects', title: 'Link Prospector — Find Opportunities', description: 'AI-powered backlink opportunity finder using Google CSE and OpenPageRank', icon: Link, action: () => push('/dashboard/backlinks'), category: 'navigation', keywords: ['backlinks', 'link building', 'seo', 'outreach', 'prospects', 'domain authority', 'resource page', 'guest post', 'link prospector'] },
    { id: 'backlinks-outreach', title: 'Link Prospector — Outreach', description: 'Manage link building outreach emails with pre-filled templates', icon: Link, action: () => push('/dashboard/backlinks?tab=outreach'), category: 'navigation', keywords: ['backlinks', 'outreach', 'email', 'link building', 'guest post', 'resource page', 'broken link', 'template'] },
    // Prompt Intelligence (Phase 96)
    { id: 'prompts-discovery', title: 'Prompt Intelligence — Discover Prompts', description: 'Generate AI prompt templates and discover which prompts trigger brand mentions', icon: Sparkles, action: () => push('/dashboard/prompts'), category: 'navigation', keywords: ['prompt', 'ai prompts', 'brand visibility', 'chatgpt', 'perplexity', 'discover', 'generate', 'prompt intelligence'] },
    { id: 'prompts-gaps', title: 'Prompt Intelligence — Gap Analysis', description: 'See which prompt categories your brand is missing and competitor visibility data', icon: Sparkles, action: () => push('/dashboard/prompts?tab=gaps'), category: 'navigation', keywords: ['prompt', 'gaps', 'analysis', 'competitors', 'visibility', 'missing', 'coverage', 'prompt intelligence', 'ai search'] },
    // Algorithm Sentinel (Phase 97)
    { id: 'sentinel-health', title: 'Algorithm Sentinel — Site Health', description: 'Monitor site health score, GSC metrics, and Core Web Vitals', icon: ShieldExclamation, action: () => push('/dashboard/sentinel'), category: 'navigation', keywords: ['sentinel', 'site health', 'algorithm', 'google update', 'ranking', 'traffic', 'cwv', 'core web vitals', 'gsc', 'search console', 'monitor'] },
    { id: 'sentinel-alerts', title: 'Algorithm Sentinel — Alerts', description: 'View unacknowledged ranking drops, traffic drops, and algorithm correlations', icon: ShieldExclamation, action: () => push('/dashboard/sentinel?tab=alerts'), category: 'navigation', keywords: ['sentinel', 'alerts', 'ranking drop', 'traffic drop', 'crawl errors', 'algorithm update', 'critical', 'warning', 'regression', 'monitor'] },
    // Autonomous A/B Testing & Self-Healing Agent (Phase 98)
    { id: 'experiments-ab', title: 'Experiments — A/B Testing', description: 'Create and manage SEO A/B experiments (title tags, H1, schema, meta)', icon: Beaker, action: () => push('/dashboard/experiments'), category: 'navigation', keywords: ['experiments', 'ab testing', 'seo', 'title tag', 'h1', 'schema', 'meta description', 'geo score', 'test variant'] },
    { id: 'experiments-healing', title: 'Experiments — Self-Healing', description: 'Analyse any URL for SEO issues and get instant fix suggestions', icon: Beaker, action: () => push('/dashboard/experiments?tab=healing'), category: 'navigation', keywords: ['healing', 'self heal', 'seo issues', 'fix', 'missing meta', 'broken schema', 'geo score', 'quality score', 'url analysis'] },
    { id: 'experiments-dogfood', title: 'Experiments — Dog-food Check', description: 'Run all Synthex analysers against synthex.social to check our own scores', icon: Beaker, action: () => push('/dashboard/experiments?tab=dogfood'), category: 'navigation', keywords: ['dogfood', 'dog food', 'synthex', 'self check', 'geo score', 'eeat', 'authority', 'quality gate', 'own site'] },
    // Bayesian Optimisation (Phase 103)
    { id: 'bo-dashboard', title: 'AI Optimisation Dashboard', description: 'Bayesian parameter optimisation — view learning state and run history', icon: Brain, action: () => push('/dashboard/optimisation'), category: 'navigation', keywords: ['bayesian', 'optimisation', 'bo', 'adaptive', 'learning', 'weights', 'parameters', 'ai'] },
    { id: 'bo-run-optimisation', title: 'Run Optimisation', description: 'Trigger a Bayesian optimisation run for your organisation', icon: Brain, action: () => push('/dashboard/optimisation'), category: 'actions', keywords: ['bayesian', 'optimise', 'run', 'trigger', 'parameters', 'weights', 'learning'] },
    // Prophet Time-Series Forecasting (Phase 106)
    { id: 'forecasting-dashboard', title: 'Forecasting Dashboard', description: 'Prophet time-series forecasting — predict engagement and reach trends', icon: TrendingUp, action: () => push('/dashboard/forecasting'), category: 'navigation', keywords: ['forecast', 'predict', 'prophet', 'time-series', 'trend'] },
    { id: 'forecasting-train', title: 'Train Forecast Model', description: 'Build a new Prophet model on your platform metrics', icon: TrendingUp, action: () => push('/dashboard/forecasting'), category: 'actions', keywords: ['forecast', 'train', 'prophet', 'model', 'build'] },
    { id: 'forecasting-predict', title: 'Generate Forecast', description: 'Generate a 7-90 day forecast from a trained model', icon: TrendingUp, action: () => push('/dashboard/forecasting'), category: 'actions', keywords: ['forecast', 'generate', '7 day', '30 day', '90 day'] },
    // Citation Performance Dashboard (Phase 99)
    { id: 'citation-dashboard', title: 'Citation Dashboard', description: 'Unified GEO + SEO + citation command centre with live agent activity', icon: CommandLine, action: () => push('/dashboard/citation'), category: 'navigation', keywords: ['citation', 'dashboard', 'command centre', 'geo', 'seo', 'agent activity', 'overview', 'performance', 'opportunities'] },
    { id: 'citation-opportunities', title: 'Citation Opportunities', description: 'See unfulfilled citation opportunities across all GEO modules', icon: CommandLine, action: () => push('/dashboard/citation'), category: 'navigation', keywords: ['citation', 'opportunities', 'pipeline', 'actions', 'improve', 'geo'] },
    // GEO Content Optimiser v2 (Phase 87)
    { id: 'geo-optimiser', title: 'GEO Content Optimiser', description: 'Score content with Princeton 9-tactic GEO framework and get AI rewrites', icon: Zap, action: () => push('/dashboard/geo/optimiser'), category: 'navigation', keywords: ['geo', 'optimiser', 'content', 'score', 'princeton', 'tactic', 'rewrite', 'ai', 'citation', 'passage', 'statistics'] },
    { id: 'authority-analysis', title: 'Authority Analysis', description: 'Validate claims and generate citations from authoritative sources', icon: Shield, action: () => push('/dashboard/authority'), category: 'navigation', keywords: ['authority', 'claims', 'validate', 'citations', 'sources', 'verify', 'credibility'] },
    { id: 'validate-claims', title: 'Validate Claims', description: 'Check content claims against government, academic, and industry sources', icon: Shield, action: () => push('/dashboard/authority'), category: 'actions', keywords: ['validate', 'claims', 'verify', 'authority', 'fact check', 'sources', 'academic', 'government'] },
    { id: 'generate-citations', title: 'Generate Citations', description: 'Auto-generate formatted footnotes and inline citations', icon: Shield, action: () => push('/dashboard/authority'), category: 'actions', keywords: ['citations', 'generate', 'footnotes', 'references', 'authority', 'apa', 'chicago'] },
    { id: 'scheduled-audits', title: 'Scheduled Audits', description: 'Automated recurring SEO audits with regression alerts', icon: Calendar, action: () => push('/dashboard/seo/scheduled-audits'), category: 'navigation', keywords: ['scheduled', 'audits', 'automation', 'alerts', 'regression', 'monitoring', 'recurring', 'cron', 'seo'] },

    // Workflows (AI Agents — Phase 62)
    { id: 'workflows', title: 'Open Workflows', description: 'View and manage AI workflow executions', icon: GitPullRequest, action: () => push('/dashboard/workflows'), category: 'navigation', keywords: ['workflow', 'automation', 'ai', 'execution', 'steps', 'agents'] },
    { id: 'new-workflow', title: 'New Workflow', description: 'Start a new AI workflow execution', icon: Plus, action: () => push('/dashboard/workflows?action=new'), category: 'actions', keywords: ['workflow', 'new', 'start', 'create', 'automation', 'ai'] },
    { id: 'pending-approvals-workflows', title: 'View Pending Approvals', description: 'See workflow steps waiting for your approval', icon: GitPullRequest, action: () => push('/dashboard/workflows?filter=waiting_approval'), category: 'navigation', keywords: ['workflow', 'approval', 'pending', 'waiting', 'review', 'approve'] },

    // Actions
    { id: 'new-content', title: 'Create New Content', description: 'Generate AI-powered content', icon: Plus, action: () => { push('/dashboard/content'); notify.custom('Ready to create amazing content!'); }, category: 'actions', keywords: ['new', 'create', 'generate', 'ai'] },
    { id: 'add-keyword', title: 'Add Tracked Keyword', description: 'Start monitoring a new keyword or hashtag', icon: Bell, action: () => push('/dashboard/listening?action=add'), category: 'actions', keywords: ['add', 'track', 'keyword', 'hashtag', 'monitor', 'listening', 'brand'] },
    { id: 'create-bio-page', title: 'Create Bio Page', description: 'Create a new Link in Bio landing page', icon: Link2, action: () => push('/dashboard/bio?action=create'), category: 'actions', keywords: ['create', 'new', 'bio', 'link', 'page', 'landing', 'linktree'] },
    { id: 'analyze-trends', title: 'Analyze Viral Trends', description: 'Discover what\'s trending now', icon: TrendingUp, action: () => { push('/dashboard/patterns'); notify.loading('Analyzing trending patterns...'); }, category: 'actions', keywords: ['trends', 'viral', 'popular', 'analyze'] },
    { id: 'quick-post', title: 'Quick Post', description: 'Post to all platforms', icon: Sparkles, action: () => { const event = new CustomEvent('openQuickPost'); window.dispatchEvent(event); }, category: 'actions', keywords: ['post', 'quick', 'publish', 'share'] },
    { id: 'generate-image', title: 'Generate Image', description: 'Create a new AI image', icon: Sparkles, action: () => push('/dashboard/ai-images'), category: 'actions', keywords: ['create', 'new', 'image', 'generate', 'ai'] },

    // Settings
    { id: 'settings', title: 'Settings', icon: Settings, action: () => push('/dashboard/settings'), category: 'settings', keywords: ['settings', 'preferences', 'config'] },
    { id: 'profile', title: 'Profile', icon: User, action: () => push('/dashboard/settings#profile'), category: 'settings', keywords: ['profile', 'account', 'user'] },
    { id: 'billing', title: 'Billing', description: 'Manage subscription and payments', icon: CreditCard, action: () => push('/dashboard/billing'), category: 'settings', keywords: ['billing', 'subscription', 'payment', 'invoice'] },
    { id: 'logout', title: 'Sign Out', icon: LogOut, action: () => { localStorage.clear(); notify.logoutSuccess(); push('/login'); }, category: 'settings', keywords: ['logout', 'signout', 'exit'] },

    // Help
    { id: 'help', title: 'Help & Support', description: 'Get help and documentation', icon: HelpCircle, action: () => push('/dashboard/help'), category: 'help', keywords: ['help', 'support', 'docs', 'faq'] },
  ];
}
