/**
 * Directory Database — Curated Directory Templates (Phase 94)
 *
 * A hand-curated list of high-authority directories known for AI search engine
 * indexing and authoritative backlink generation. Used to pre-populate the
 * directory tracker.
 *
 * @module lib/awards/directory-database
 */

export interface DirectoryTemplate {
  directoryName: string;
  directoryUrl: string;
  category: string;
  domainAuthority: number;
  isFree: boolean;
  isAiIndexed: boolean;   // Known to be cited by ChatGPT, Perplexity, or Google AIO
  description: string;
  country: 'Australia' | 'Global';
  industry: string[];
}

export const DIRECTORY_TEMPLATES: DirectoryTemplate[] = [
  // ─── High-DA Global Directories ───────────────────────────────────────────
  {
    directoryName: 'Crunchbase',
    directoryUrl: 'https://www.crunchbase.com',
    category: 'Company & Startup Profiles',
    domainAuthority: 91,
    isFree: true,
    isAiIndexed: true,
    description: 'The leading platform for company intelligence and startup profiles. Heavily cited by ChatGPT and Perplexity for company facts.',
    country: 'Global',
    industry: ['Startup', 'Technology', 'SaaS', 'AI', 'Marketing'],
  },
  {
    directoryName: 'G2',
    directoryUrl: 'https://www.g2.com',
    category: 'Software Reviews',
    domainAuthority: 90,
    isFree: true,
    isAiIndexed: true,
    description: 'The world\'s largest tech marketplace. G2 profiles rank for branded and category queries and are cited in AI-generated software comparisons.',
    country: 'Global',
    industry: ['SaaS', 'Marketing Software', 'Technology', 'AI Tools'],
  },
  {
    directoryName: 'Clutch.co',
    directoryUrl: 'https://clutch.co',
    category: 'B2B Service Providers',
    domainAuthority: 84,
    isFree: true,
    isAiIndexed: true,
    description: 'Leading B2B review platform. Clutch badges and profiles are frequently cited in AI-generated "best software" and "top companies" answers.',
    country: 'Global',
    industry: ['Marketing', 'SaaS', 'Digital Services', 'Automation'],
  },
  {
    directoryName: 'Capterra',
    directoryUrl: 'https://www.capterra.com',
    category: 'Software Reviews & Comparisons',
    domainAuthority: 89,
    isFree: true,
    isAiIndexed: true,
    description: 'Gartner-owned software review platform. Capterra listings appear prominently in AI-generated software recommendation responses.',
    country: 'Global',
    industry: ['SaaS', 'Marketing Automation', 'CRM', 'Business Software'],
  },
  {
    directoryName: 'Trustpilot',
    directoryUrl: 'https://www.trustpilot.com',
    category: 'Customer Reviews',
    domainAuthority: 93,
    isFree: true,
    isAiIndexed: true,
    description: 'Global review platform with extremely high DA. Trustpilot reviews are cited by AI models when answering questions about company trustworthiness.',
    country: 'Global',
    industry: ['All Industries', 'SaaS', 'E-commerce', 'Services'],
  },
  {
    directoryName: 'AngelList / Wellfound',
    directoryUrl: 'https://wellfound.com',
    category: 'Startup & Talent Marketplace',
    domainAuthority: 86,
    isFree: true,
    isAiIndexed: true,
    description: 'Wellfound (formerly AngelList Talent) is a primary reference for startup company data cited by AI engines like Perplexity.',
    country: 'Global',
    industry: ['Startup', 'Technology', 'SaaS', 'AI'],
  },
  {
    directoryName: 'Product Hunt',
    directoryUrl: 'https://www.producthunt.com',
    category: 'Product Discovery',
    domainAuthority: 88,
    isFree: true,
    isAiIndexed: true,
    description: 'Product Hunt listings are frequently cited by AI models when users ask about new tools. A launch creates a durable, AI-indexed profile.',
    country: 'Global',
    industry: ['SaaS', 'AI Tools', 'Productivity', 'Marketing Technology'],
  },
  {
    directoryName: 'SourceForge',
    directoryUrl: 'https://sourceforge.net',
    category: 'Open Source & Software',
    domainAuthority: 86,
    isFree: true,
    isAiIndexed: false,
    description: 'Long-standing software directory with high DA. Useful for backlinks even if not primarily an AI citation source.',
    country: 'Global',
    industry: ['Software', 'SaaS', 'Open Source', 'Technology'],
  },
  {
    directoryName: 'GetApp',
    directoryUrl: 'https://www.getapp.com',
    category: 'Business Software Reviews',
    domainAuthority: 80,
    isFree: true,
    isAiIndexed: false,
    description: 'Gartner-owned SMB-focused software directory. Provides strong category and backlink signals for SaaS products.',
    country: 'Global',
    industry: ['SaaS', 'Business Software', 'Marketing Automation'],
  },
  {
    directoryName: 'Software Advice',
    directoryUrl: 'https://www.softwareadvice.com',
    category: 'Software Buying Advice',
    domainAuthority: 81,
    isFree: true,
    isAiIndexed: false,
    description: 'Another Gartner-owned platform. Completing the Gartner trifecta (Capterra, GetApp, Software Advice) maximises review site coverage.',
    country: 'Global',
    industry: ['SaaS', 'CRM', 'Marketing Software', 'Business Software'],
  },
  {
    directoryName: 'Wikidata',
    directoryUrl: 'https://www.wikidata.org',
    category: 'Knowledge Graph Entity',
    domainAuthority: 93,
    isFree: true,
    isAiIndexed: true,
    description: 'The structured data backbone of Wikipedia. A Wikidata entity is directly consumed by AI models and is critical for Knowledge Panel eligibility.',
    country: 'Global',
    industry: ['All Industries'],
  },

  // ─── Australian Directories ───────────────────────────────────────────────
  {
    directoryName: 'StartupAUS Members Directory',
    directoryUrl: 'https://www.startupaus.org/members',
    category: 'Australian Startup Directory',
    domainAuthority: 52,
    isFree: true,
    isAiIndexed: false,
    description: 'Australia\'s peak startup advocacy body. Membership listing provides a credible Australian startup citation and backlink.',
    country: 'Australia',
    industry: ['Startup', 'Technology', 'AI', 'SaaS'],
  },
  {
    directoryName: 'Stone & Chalk Ecosystem Directory',
    directoryUrl: 'https://stoneandchalk.com.au/community',
    category: 'Australian Fintech & Tech Ecosystem',
    domainAuthority: 48,
    isFree: true,
    isAiIndexed: false,
    description: 'Stone & Chalk is Australia\'s leading startup hub. Listing in their ecosystem directory establishes E-E-A-T authority in the Australian tech scene.',
    country: 'Australia',
    industry: ['Fintech', 'Technology', 'SaaS', 'AI', 'Startup'],
  },
  {
    directoryName: 'AIIA Member Directory',
    directoryUrl: 'https://www.aiia.com.au/membership/directory',
    category: 'Australian ICT Industry',
    domainAuthority: 50,
    isFree: false,
    isAiIndexed: false,
    description: 'The Australian Information Industry Association member directory. Membership signals credibility to enterprise buyers and AI models referencing AU tech.',
    country: 'Australia',
    industry: ['Technology', 'ICT', 'SaaS', 'AI', 'Software'],
  },
  {
    directoryName: 'Seek Business Marketplace',
    directoryUrl: 'https://www.seek.com.au/business',
    category: 'Australian Business Listings',
    domainAuthority: 84,
    isFree: true,
    isAiIndexed: false,
    description: 'Seek\'s extremely high DA makes business listings valuable for local SEO and NAP consistency signals in Australia.',
    country: 'Australia',
    industry: ['All Industries', 'Business Services', 'SaaS'],
  },
  {
    directoryName: 'Yellow Pages Australia',
    directoryUrl: 'https://www.yellowpages.com.au',
    category: 'Australian Business Directory',
    domainAuthority: 70,
    isFree: true,
    isAiIndexed: false,
    description: 'Australia\'s primary online business directory. Critical for NAP consistency and local SEO, even for SaaS businesses with an Australian presence.',
    country: 'Australia',
    industry: ['All Industries', 'Local Business', 'SaaS'],
  },
  {
    directoryName: 'True Local',
    directoryUrl: 'https://www.truelocal.com.au',
    category: 'Australian Local Business',
    domainAuthority: 62,
    isFree: true,
    isAiIndexed: false,
    description: 'Australian local business directory with customer reviews. Supports NAP consistency and regional E-E-A-T signals.',
    country: 'Australia',
    industry: ['Local Business', 'Services', 'All Industries'],
  },
  {
    directoryName: 'BuiltInAustralia Tech Directory',
    directoryUrl: 'https://builtinaustralia.com',
    category: 'Australian Tech Companies',
    domainAuthority: 38,
    isFree: true,
    isAiIndexed: false,
    description: 'A curated directory of tech companies built in or operating out of Australia. Growing as an AI-citation resource for AU tech brands.',
    country: 'Australia',
    industry: ['Technology', 'SaaS', 'AI', 'Startup'],
  },

  // ─── AI-Specific Citation Directories ─────────────────────────────────────
  {
    directoryName: 'There\'s An AI For That',
    directoryUrl: 'https://theresanaiforthat.com',
    category: 'AI Tools Directory',
    domainAuthority: 71,
    isFree: true,
    isAiIndexed: true,
    description: 'The largest AI tools directory on the web. Listed tools are frequently referenced by AI models when answering "what AI tool can help me with X" queries.',
    country: 'Global',
    industry: ['AI Tools', 'SaaS', 'Marketing Technology'],
  },
  {
    directoryName: 'Futurepedia',
    directoryUrl: 'https://www.futurepedia.io',
    category: 'AI Tools Directory',
    domainAuthority: 62,
    isFree: true,
    isAiIndexed: true,
    description: 'One of the top AI tools directories by traffic. Listing here increases AI citation likelihood for marketing and productivity tool queries.',
    country: 'Global',
    industry: ['AI Tools', 'Marketing Technology', 'Productivity', 'SaaS'],
  },
  {
    directoryName: 'AI Tool Hunt',
    directoryUrl: 'https://www.aitoolhunt.com',
    category: 'AI Tools Discovery',
    domainAuthority: 45,
    isFree: true,
    isAiIndexed: false,
    description: 'Growing AI tools discovery platform. Useful for building category presence in AI tool comparison searches.',
    country: 'Global',
    industry: ['AI Tools', 'SaaS', 'Marketing'],
  },
];
