/**
 * Schema Exports Index
 *
 * Central export point for all Zod validation schemas.
 * Import from here for cleaner imports across the codebase.
 *
 * @module lib/schemas
 */

// Auth schemas - export all (base definitions)
export {
  emailSchema,
  passwordSchema,
  usernameSchema,
  uuidSchema,
  loginSchema,
  type LoginInput,
  signupSchema,
  type SignupInput,
  forgotPasswordSchema,
  type ForgotPasswordInput,
  resetPasswordSchema,
  type ResetPasswordInput,
  profileUpdateSchema,
  type ProfileUpdateInput,
  oauthPlatformSchema,
  type OAuthPlatform,
  oauthInitiateSchema,
  type OAuthInitiateInput,
  oauthCallbackSchema,
  type OAuthCallbackInput,
  oauthStateSchema,
  type OAuthStateData,
  createApiKeySchema,
  type CreateApiKeyInput,
  revokeApiKeySchema,
  type RevokeApiKeyInput,
  sessionSchema,
  type SessionData,
  verifyEmailSchema,
  type VerifyEmailInput,
  resendVerificationSchema,
  type ResendVerificationInput,
  enable2FASchema,
  type Enable2FAInput,
  verify2FASchema,
  type Verify2FAInput,
  disable2FASchema,
  type Disable2FAInput,
  validateLogin,
  validateSignup,
  validateOAuthCallback,
  safeValidate,
  formatZodErrors,
  // Response schemas for contract testing
  userResponseSchema,
  type UserResponse,
  loginResponseSchema,
  type LoginResponse,
  signupResponseSchema,
  type SignupResponse,
  getUserResponseSchema,
  type GetUserResponse,
  updateUserResponseSchema,
  type UpdateUserResponse,
  authErrorResponseSchema,
  type AuthErrorResponse,
  requestResetResponseSchema,
  type RequestResetResponse,
  resetPasswordResponseSchema,
  type ResetPasswordResponse,
  verifyEmailResponseSchema,
  type VerifyEmailResponse,
  logoutResponseSchema,
  type LogoutResponse,
} from './auth';

// Content schemas - export with prefix to avoid conflicts
export {
  platformSchema as contentPlatformSchema,
  type Platform as ContentPlatform,
  contentTypeSchema,
  type ContentType,
  contentStatusSchema,
  type ContentStatus,
  createPostSchema,
  type CreatePostInput,
  updatePostSchema,
  type UpdatePostInput,
  createCampaignSchema,
  type CreateCampaignInput,
  updateCampaignSchema,
  type UpdateCampaignInput,
  schedulePostSchema,
  type SchedulePostInput,
  bulkScheduleSchema,
  type BulkScheduleInput,
  generateContentSchema,
  type GenerateContentInput,
  optimizeContentSchema,
  type OptimizeContentInput,
  generateHashtagsSchema,
  type GenerateHashtagsInput,
  translateContentSchema,
  type TranslateContentInput,
  listPostsSchema,
  type ListPostsInput,
  listCampaignsSchema,
  type ListCampaignsInput,
  bulkDeleteSchema,
  type BulkDeleteInput,
  bulkArchiveSchema,
  type BulkArchiveInput,
  bulkUpdateStatusSchema,
  type BulkUpdateStatusInput,
  validateCreatePost,
  validateGenerateContent,
  validateCreateCampaign,
  platformLimits,
  validatePlatformLimits,
  // Response schemas for contract testing
  postResponseSchema,
  type PostResponse,
  createPostResponseSchema,
  type CreatePostResponse,
  listPostsResponseSchema,
  type ListPostsResponse,
  campaignResponseSchema,
  type CampaignResponse,
  createCampaignResponseSchema,
  type CreateCampaignResponse,
  listCampaignsResponseSchema,
  type ListCampaignsResponse,
  contentErrorResponseSchema,
  type ContentErrorResponse,
  generateContentResponseSchema,
  type GenerateContentResponse,
} from './content';

// Analytics schemas - export with prefix to avoid conflicts
export {
  platformSchema as analyticsPlatformSchema,
  type Platform as AnalyticsPlatform,
  dateRangeSchema,
  type DateRange,
  granularitySchema,
  type Granularity,
  metricTypeSchema,
  type MetricType,
  dashboardQuerySchema,
  type DashboardQueryInput,
  engagementQuerySchema,
  type EngagementQueryInput,
  performanceQuerySchema,
  type PerformanceQueryInput,
  realtimeQuerySchema,
  type RealtimeQueryInput,
  insightsQuerySchema,
  type InsightsQueryInput,
  comparisonQuerySchema,
  type ComparisonQueryInput,
  trendsQuerySchema,
  type TrendsQueryInput,
  exportFormatSchema,
  type ExportFormat,
  exportQuerySchema,
  type ExportQueryInput,
  bulkExportSchema,
  type BulkExportInput,
  generateReportSchema,
  type GenerateReportInput,
  audienceQuerySchema,
  type AudienceQueryInput,
  competitorAnalysisSchema,
  type CompetitorAnalysisInput,
  validateDashboardQuery,
  validateExportQuery,
  validateComparisonQuery,
  validateGenerateReport,
  periodToDateRange,
  getDefaultMetrics,
  // Response schemas for contract testing
  metricDataPointSchema,
  type MetricDataPoint,
  dashboardOverviewResponseSchema,
  type DashboardOverviewResponse,
  engagementAnalyticsResponseSchema,
  type EngagementAnalyticsResponse,
  analyticsExportResponseSchema,
  type AnalyticsExportResponse,
  analyticsErrorResponseSchema,
  type AnalyticsErrorResponse,
} from './analytics';

// Common schemas - shared patterns
export {
  paginationSchema,
  type Pagination,
  successResponseSchema,
  dataResponseSchema,
  paginatedResponseSchema,
  errorResponseSchema,
  type ErrorResponse,
  failureResponseSchema,
  platformEnumSchema,
  type PlatformEnum,
  platformConnectionSchema,
  type PlatformConnection,
  listPlatformConnectionsResponseSchema,
  seoAuditSchema,
  seoAuditResponseSchema,
  geoAnalysisSchema,
  geoAnalysisResponseSchema,
  revenueEntrySchema,
  sponsorSchema,
  affiliateSchema,
  revenueResponseSchema,
  sponsorResponseSchema,
  affiliateResponseSchema,
  aiConversationSchema,
  aiMessageSchema,
  aiChatResponseSchema,
  reportSchema,
  reportResponseSchema,
  teamMemberSchema,
  organizationSchema,
  healthCheckResponseSchema,
} from './common';

// Re-export Zod for convenience
export { z } from 'zod';
export type { ZodError, ZodSchema, ZodType } from 'zod';
