-- =============================================================================
-- Migration: Performance Indexes (Defensive)
-- Generated by: sql-hardener skill
-- Date: 2026-02-15
-- Updated: 2026-02-19 (Fully defensive - checks table/column existence)
-- =============================================================================
--
-- Creates supplementary indexes for performance optimization.
-- All operations check for table/column existence to prevent errors when
-- schema isn't fully synced (e.g., Prisma hasn't pushed yet).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. TIMESTAMP INDEXES (Critical for date-range queries)
-- -----------------------------------------------------------------------------

-- posts.published_at (DESC for "recent posts" queries)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'posts' AND column_name = 'published_at')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_posts_published_at')
  THEN
    CREATE INDEX idx_posts_published_at ON posts(published_at DESC NULLS LAST);
    RAISE NOTICE 'Created index idx_posts_published_at';
  END IF;
END $$;

-- posts.scheduled_at (for scheduler queries - partial index)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'posts' AND column_name = 'scheduled_at')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_posts_scheduled_at')
  THEN
    CREATE INDEX idx_posts_scheduled_at ON posts(scheduled_at) WHERE scheduled_at IS NOT NULL;
    RAISE NOTICE 'Created index idx_posts_scheduled_at';
  END IF;
END $$;

-- api_usage.created_at (DESC for recent usage queries)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'api_usage' AND column_name = 'created_at')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_api_usage_created_at')
  THEN
    CREATE INDEX idx_api_usage_created_at ON api_usage(created_at DESC);
    RAISE NOTICE 'Created index idx_api_usage_created_at';
  END IF;
END $$;

-- analytics_events.timestamp (for time-series queries)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'analytics_events' AND column_name = 'timestamp')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_analytics_events_timestamp')
  THEN
    CREATE INDEX idx_analytics_events_timestamp ON analytics_events(timestamp DESC);
    RAISE NOTICE 'Created index idx_analytics_events_timestamp';
  END IF;
END $$;

-- notifications.created_at (for recent notifications)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'notifications' AND column_name = 'created_at')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_notifications_created_at')
  THEN
    CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
    RAISE NOTICE 'Created index idx_notifications_created_at';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 2. STATUS/TYPE INDEXES (For filtering queries)
-- -----------------------------------------------------------------------------

-- campaigns.status
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'campaigns' AND column_name = 'status')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_campaigns_status')
  THEN
    CREATE INDEX idx_campaigns_status ON campaigns(status);
    RAISE NOTICE 'Created index idx_campaigns_status';
  END IF;
END $$;

-- calendar_posts.status
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'calendar_posts' AND column_name = 'status')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_calendar_posts_status')
  THEN
    CREATE INDEX idx_calendar_posts_status ON calendar_posts(status);
    RAISE NOTICE 'Created index idx_calendar_posts_status';
  END IF;
END $$;

-- calendar_posts partial index for pending/scheduled (most common query)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'calendar_posts' AND column_name = 'scheduled_for')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'calendar_posts' AND column_name = 'status')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_calendar_posts_pending')
  THEN
    CREATE INDEX idx_calendar_posts_pending ON calendar_posts(scheduled_for) WHERE status IN ('pending', 'scheduled');
    RAISE NOTICE 'Created index idx_calendar_posts_pending';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 3. COMPOSITE INDEXES (For common query patterns)
-- -----------------------------------------------------------------------------

-- Campaigns by user and status (dashboard query)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'campaigns' AND column_name = 'user_id')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'campaigns' AND column_name = 'status')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'campaigns' AND column_name = 'created_at')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_campaigns_user_status')
  THEN
    CREATE INDEX idx_campaigns_user_status ON campaigns(user_id, status, created_at DESC);
    RAISE NOTICE 'Created index idx_campaigns_user_status';
  END IF;
END $$;

-- Analytics by user, content, and date (reporting)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'analytics_events' AND column_name = 'user_id')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'analytics_events' AND column_name = 'content_id')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'analytics_events' AND column_name = 'timestamp')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_analytics_events_user_content_date')
  THEN
    CREATE INDEX idx_analytics_events_user_content_date ON analytics_events(user_id, content_id, timestamp DESC);
    RAISE NOTICE 'Created index idx_analytics_events_user_content_date';
  END IF;
END $$;

-- Platform connections active lookup
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'platform_connections' AND column_name = 'user_id')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'platform_connections' AND column_name = 'platform')
  AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'platform_connections' AND column_name = 'is_active')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_platform_connections_active')
  THEN
    CREATE INDEX idx_platform_connections_active ON platform_connections(user_id, platform) WHERE is_active = true;
    RAISE NOTICE 'Created index idx_platform_connections_active';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. JSONB GIN INDEXES (For JSON queries)
-- -----------------------------------------------------------------------------

-- posts.metadata (for filtering by hashtags, mentions, etc.)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'posts' AND column_name = 'metadata')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_posts_metadata_gin')
  THEN
    CREATE INDEX idx_posts_metadata_gin ON posts USING gin(metadata jsonb_path_ops);
    RAISE NOTICE 'Created index idx_posts_metadata_gin';
  END IF;
END $$;

-- campaigns.settings (for campaign configuration filtering)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'campaigns' AND column_name = 'settings')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_campaigns_settings_gin')
  THEN
    CREATE INDEX idx_campaigns_settings_gin ON campaigns USING gin(settings jsonb_path_ops);
    RAISE NOTICE 'Created index idx_campaigns_settings_gin';
  END IF;
END $$;

-- users.preferences (for feature flags, preferences)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'preferences')
  AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_users_preferences_gin')
  THEN
    CREATE INDEX idx_users_preferences_gin ON users USING gin(preferences jsonb_path_ops);
    RAISE NOTICE 'Created index idx_users_preferences_gin';
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 5. ANALYZE TABLES (Only if they exist)
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  tables TEXT[] := ARRAY['users', 'personas', 'posts', 'campaigns', 'calendar_posts',
                         'analytics_events', 'platform_connections', 'api_usage', 'notifications'];
  t TEXT;
BEGIN
  FOREACH t IN ARRAY tables LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
      EXECUTE format('ANALYZE %I', t);
      RAISE NOTICE 'Analyzed table %', t;
    END IF;
  END LOOP;
END $$;
