-- =============================================================================
-- Migration: Performance Indexes
-- Generated by: sql-hardener skill
-- Date: 2026-02-15
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. FOREIGN KEY INDEXES (Critical for JOIN performance)
-- -----------------------------------------------------------------------------

-- team_members.team_id - frequently joined
CREATE INDEX IF NOT EXISTS idx_team_members_team_id
  ON team_members(team_id);

-- team_members composite for common query pattern
CREATE INDEX IF NOT EXISTS idx_team_members_team_user
  ON team_members(team_id, user_id);

-- scheduled_posts.content_id
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_content_id
  ON scheduled_posts(content_id);

-- scheduled_posts.campaign_id
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_campaign_id
  ON scheduled_posts(campaign_id);

-- content.persona_id
CREATE INDEX IF NOT EXISTS idx_content_persona_id
  ON content(persona_id);

-- analytics.platform
CREATE INDEX IF NOT EXISTS idx_analytics_platform
  ON analytics(platform);

-- -----------------------------------------------------------------------------
-- 2. TIMESTAMP INDEXES (Critical for date-range queries)
-- -----------------------------------------------------------------------------

-- content.published_at (DESC for "recent posts" queries)
CREATE INDEX IF NOT EXISTS idx_content_published_at
  ON content(published_at DESC NULLS LAST);

-- content.scheduled_for (for scheduler queries)
CREATE INDEX IF NOT EXISTS idx_content_scheduled_for
  ON content(scheduled_for)
  WHERE scheduled_for IS NOT NULL;

-- api_usage.created_at (DESC for recent usage queries)
CREATE INDEX IF NOT EXISTS idx_api_usage_created_at
  ON api_usage(created_at DESC);

-- analytics.recorded_at (for time-series queries)
CREATE INDEX IF NOT EXISTS idx_analytics_recorded_at
  ON analytics(recorded_at DESC);

-- notifications.created_at (for recent notifications)
CREATE INDEX IF NOT EXISTS idx_notifications_created_at
  ON notifications(created_at DESC);

-- -----------------------------------------------------------------------------
-- 3. STATUS/TYPE INDEXES (For filtering queries)
-- -----------------------------------------------------------------------------

-- campaigns.status
CREATE INDEX IF NOT EXISTS idx_campaigns_status
  ON campaigns(status);

-- scheduled_posts.status with partial for pending
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_status
  ON scheduled_posts(status);

-- Partial index for pending posts (most common query)
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_pending
  ON scheduled_posts(scheduled_time)
  WHERE status = 'pending';

-- notifications unread (partial index)
CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON notifications(user_id, created_at DESC)
  WHERE is_read = false;

-- content.status
CREATE INDEX IF NOT EXISTS idx_content_status_platform
  ON content(status, platform);

-- -----------------------------------------------------------------------------
-- 4. COMPOSITE INDEXES (For common query patterns)
-- -----------------------------------------------------------------------------

-- Content by user and status (dashboard query)
CREATE INDEX IF NOT EXISTS idx_content_user_status
  ON content(user_id, status, created_at DESC);

-- Campaigns by user and status (dashboard query)
CREATE INDEX IF NOT EXISTS idx_campaigns_user_status
  ON campaigns(user_id, status, created_at DESC);

-- Analytics by user, content, and date (reporting)
CREATE INDEX IF NOT EXISTS idx_analytics_user_content_date
  ON analytics(user_id, content_id, recorded_at DESC);

-- Platform connections active lookup
CREATE INDEX IF NOT EXISTS idx_platform_connections_active
  ON platform_connections(user_id, platform)
  WHERE is_active = true;

-- -----------------------------------------------------------------------------
-- 5. JSONB GIN INDEXES (For JSON queries)
-- -----------------------------------------------------------------------------

-- content.metadata (for filtering by hashtags, mentions, etc.)
CREATE INDEX IF NOT EXISTS idx_content_metadata_gin
  ON content USING gin(metadata jsonb_path_ops);

-- campaigns.target_audience (for audience filtering)
CREATE INDEX IF NOT EXISTS idx_campaigns_target_audience_gin
  ON campaigns USING gin(target_audience jsonb_path_ops);

-- viral_patterns.pattern_data (for pattern matching)
CREATE INDEX IF NOT EXISTS idx_viral_patterns_data_gin
  ON viral_patterns USING gin(pattern_data jsonb_path_ops);

-- profiles.settings (for feature flags, preferences)
CREATE INDEX IF NOT EXISTS idx_profiles_settings_gin
  ON profiles USING gin(settings jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- 6. UNIQUE CONSTRAINTS (Data integrity)
-- -----------------------------------------------------------------------------

-- Ensure unique team membership (if not already exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'team_members_team_user_unique'
  ) THEN
    ALTER TABLE team_members
      ADD CONSTRAINT team_members_team_user_unique
      UNIQUE (team_id, user_id);
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 7. ANALYZE TABLES (Update statistics for query planner)
-- -----------------------------------------------------------------------------

ANALYZE profiles;
ANALYZE personas;
ANALYZE content;
ANALYZE campaigns;
ANALYZE scheduled_posts;
ANALYZE analytics;
ANALYZE platform_connections;
ANALYZE api_usage;
ANALYZE team_members;
ANALYZE notifications;
ANALYZE viral_patterns;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- List all indexes
-- SELECT tablename, indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public'
-- ORDER BY tablename, indexname;

-- Check index usage (run after some queries)
-- SELECT
--   schemaname, tablename, indexname,
--   idx_scan, idx_tup_read, idx_tup_fetch
-- FROM pg_stat_user_indexes
-- WHERE schemaname = 'public'
-- ORDER BY idx_scan DESC;
