-- =============================================================================
-- Migration: Security Hardening
-- Generated by: sql-hardener skill
-- Date: 2026-02-15
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. ENABLE RLS ON MISSING TABLES
-- -----------------------------------------------------------------------------

-- team_members: CRITICAL - contains team membership data
ALTER TABLE IF EXISTS team_members ENABLE ROW LEVEL SECURITY;

-- viral_patterns: Optional - public read, admin write
ALTER TABLE IF EXISTS viral_patterns ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- 2. RLS POLICIES FOR team_members
-- -----------------------------------------------------------------------------

-- Drop existing policies if any
DROP POLICY IF EXISTS "team_members_select_own_team" ON team_members;
DROP POLICY IF EXISTS "team_members_insert_admin" ON team_members;
DROP POLICY IF EXISTS "team_members_update" ON team_members;
DROP POLICY IF EXISTS "team_members_delete_admin" ON team_members;
DROP POLICY IF EXISTS "team_members_service_bypass" ON team_members;

-- SELECT: Team members can view their own team
CREATE POLICY "team_members_select_own_team"
  ON team_members FOR SELECT
  USING (
    user_id = auth.uid()
    OR team_id IN (
      SELECT tm.team_id FROM team_members tm WHERE tm.user_id = auth.uid()
    )
  );

-- INSERT: Team admins/owners can invite, or user can accept their own invite
CREATE POLICY "team_members_insert_admin"
  ON team_members FOR INSERT
  WITH CHECK (
    -- Admins/owners of the team can add members
    EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.team_id = team_members.team_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('admin', 'owner')
    )
    -- Or user is accepting their own invitation
    OR user_id = auth.uid()
  );

-- UPDATE: Members can update own record, admins can update anyone in team
CREATE POLICY "team_members_update"
  ON team_members FOR UPDATE
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.team_id = team_members.team_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('admin', 'owner')
    )
  );

-- DELETE: Only admins/owners can remove team members
CREATE POLICY "team_members_delete_admin"
  ON team_members FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.team_id = team_members.team_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('admin', 'owner')
    )
    -- Or member removing themselves
    OR user_id = auth.uid()
  );

-- Service role bypass for backend operations
CREATE POLICY "team_members_service_bypass"
  ON team_members FOR ALL
  USING (auth.role() = 'service_role');

-- -----------------------------------------------------------------------------
-- 3. RLS POLICIES FOR viral_patterns (public read, admin write)
-- -----------------------------------------------------------------------------

DROP POLICY IF EXISTS "viral_patterns_public_read" ON viral_patterns;
DROP POLICY IF EXISTS "viral_patterns_admin_write" ON viral_patterns;
DROP POLICY IF EXISTS "viral_patterns_service_bypass" ON viral_patterns;

-- Anyone can read viral patterns (they're shared knowledge)
CREATE POLICY "viral_patterns_public_read"
  ON viral_patterns FOR SELECT
  USING (true);

-- Only service role can modify (backend scraper)
CREATE POLICY "viral_patterns_service_bypass"
  ON viral_patterns FOR ALL
  USING (auth.role() = 'service_role');

-- -----------------------------------------------------------------------------
-- 4. STRENGTHEN EXISTING POLICIES
-- -----------------------------------------------------------------------------

-- Add service role bypass to all user-data tables for backend operations
DO $$
DECLARE
  tbl TEXT;
  tables TEXT[] := ARRAY[
    'profiles', 'personas', 'content', 'campaigns',
    'scheduled_posts', 'analytics', 'platform_connections',
    'api_usage', 'notifications'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables
  LOOP
    -- Check if policy exists before creating
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE tablename = tbl AND policyname = tbl || '_service_bypass'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR ALL USING (auth.role() = ''service_role'')',
        tbl || '_service_bypass',
        tbl
      );
    END IF;
  END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 5. ADD NOT NULL CONSTRAINTS (with safety checks)
-- -----------------------------------------------------------------------------

-- Only apply if column is currently nullable and has no NULL values
DO $$
BEGIN
  -- personas.user_id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'personas' AND column_name = 'user_id' AND is_nullable = 'YES'
  ) AND NOT EXISTS (
    SELECT 1 FROM personas WHERE user_id IS NULL
  ) THEN
    ALTER TABLE personas ALTER COLUMN user_id SET NOT NULL;
  END IF;

  -- content.user_id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'content' AND column_name = 'user_id' AND is_nullable = 'YES'
  ) AND NOT EXISTS (
    SELECT 1 FROM content WHERE user_id IS NULL
  ) THEN
    ALTER TABLE content ALTER COLUMN user_id SET NOT NULL;
  END IF;

  -- campaigns.user_id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'campaigns' AND column_name = 'user_id' AND is_nullable = 'YES'
  ) AND NOT EXISTS (
    SELECT 1 FROM campaigns WHERE user_id IS NULL
  ) THEN
    ALTER TABLE campaigns ALTER COLUMN user_id SET NOT NULL;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 6. CREATE updated_at TRIGGER FUNCTION
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables with updated_at column
DO $$
DECLARE
  tbl TEXT;
  tables TEXT[] := ARRAY[
    'profiles', 'personas', 'content', 'viral_patterns', 'campaigns'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables
  LOOP
    -- Drop existing trigger if any
    EXECUTE format('DROP TRIGGER IF EXISTS set_updated_at ON %I', tbl);

    -- Create new trigger
    EXECUTE format(
      'CREATE TRIGGER set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION handle_updated_at()',
      tbl
    );
  END LOOP;
END $$;

-- =============================================================================
-- VERIFICATION QUERIES (run after migration)
-- =============================================================================

-- Check RLS status
-- SELECT tablename,
--        CASE WHEN relrowsecurity THEN '✓' ELSE '✗' END as rls
-- FROM pg_tables t
-- LEFT JOIN pg_class c ON c.relname = t.tablename
-- WHERE t.schemaname = 'public';

-- Check policies
-- SELECT tablename, policyname, cmd FROM pg_policies WHERE schemaname = 'public';
