'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useState } from 'react';

interface DemoConversionCardProps {
  businessName: string;
  caption: string;
  onReset: () => void;
}

const PLATFORM_ICONS = [
  'instagram',
  'facebook',
  'tiktok',
  'youtube',
  'twitter',
  'linkedin',
  'pinterest',
  'reddit',
  'threads',
] as const;

export function DemoConversionCard({
  businessName,
  caption,
  onReset,
}: DemoConversionCardProps) {
  const [copied, setCopied] = useState(false);

  const handleShare = async () => {
    try {
      await navigator.clipboard.writeText(
        `${businessName}\n\n${caption}\n\nGenerated by Synthex — synthex.social`
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access denied — silently skip
    }
  };

  return (
    <div className="mt-3 rounded-2xl border border-amber-500/20 bg-charcoal-800/80 p-4 space-y-3">
      {/* Platform icons */}
      <div className="flex items-center gap-1.5 justify-center flex-wrap">
        {PLATFORM_ICONS.map(platform => (
          <Image
            key={platform}
            src={`/icons/3d/platforms/${platform}.svg`}
            alt={platform}
            width={20}
            height={20}
            className="opacity-70"
          />
        ))}
      </div>

      {/* Social proof */}
      <p className="text-center text-xs text-white/50">
        Join <span className="text-amber-400 font-medium">5,000+</span>{' '}
        businesses automating their content
      </p>

      {/* Primary CTA */}
      <Link
        href="/signup"
        className="flex items-center justify-center gap-2 w-full rounded-xl bg-orange-500 hover:bg-orange-400 active:bg-orange-600 transition-colors py-2.5 text-sm font-semibold text-charcoal-900"
      >
        Start your free trial →
      </Link>

      {/* Trust line */}
      <p className="text-center text-[10px] text-white/30">
        No credit card required · Cancel anytime
      </p>

      {/* Secondary actions */}
      <div className="flex items-center justify-between pt-1 border-t border-white/[0.06]">
        <button
          onClick={handleShare}
          className="text-[11px] text-white/30 hover:text-white/60 transition-colors"
        >
          {copied ? '✓ Copied' : 'Share result'}
        </button>
        <button
          onClick={onReset}
          className="text-[11px] text-white/30 hover:text-amber-400 transition-colors"
        >
          Try another →
        </button>
      </div>
    </div>
  );
}
